### ISSUE TITLE
Weird fonts

### ISSUE THREAD

**Issue by peterwilfride** [lapce/lapce#457] opened 2022-04-27 00:14 UTC
![1651018245_grim](https://user-images.githubusercontent.com/41086317/165413054-545026f1-3ee6-48db-b188-6872c3dfba21.png)

I just clone and build, but when I start ./lapce from terminal the fonts are messed up.

system info:
OS: EndeavourOS Linux x86_64
WM: sway
Terminal: alacritty
Terminal Font: Fira Code
CPU: Intel i3-2310M (4) @ 2.100GHz
GPU: Intel 2nd Generation Core Processor Family

**Comment by zhaojiangbin** [comment] 2022-04-27 04:01
See #450.

**Comment by bugadani** [comment] 2022-04-27 07:08
Yes, this is a duplicate of #450

**Closed by bugadani** 2022-04-27 07:08 UTC
Labels: C-bug, duplicate, A-ui
