### ISSUE TITLE
Add Drag-and-Drop File Support

### ISSUE THREAD

**Issue by maddes8cht** [lapce/lapce#2556] opened 2023-08-19 19:11 UTC
I immediately fell in love with this super fast editor.

The only thing I miss:
In every other GUI editor I know, you can drop files onto the open editor window to open that file (in a new tab, if the editor has tabs).
This is very convenient.

Please add that in lapce.

Thanks for your great work !

**Comment by panekj** [comment] 2023-08-19 19:12
Duplicate of #1181

**Closed by panekj** 2023-08-19 19:12 UTC
Labels: C-feature
