### ISSUE TITLE
feature Windows protected your PC

### ISSUE THREAD

**Issue by MrScrappy** [lapce/lapce#1535] opened 2022-10-16 05:04 UTC
## Is your feature request related to a problem? Please describe.

When installing on Windows, it throws the message.

"Windows protected your PC

Microsoft Defender SmartScreen prevented an unknown application from starting. Running this application could put your PC at risk.

App:
lapce-windows.msi
Editor:
unknown
"

I was able to install it and I liked it a lot, my friend tried to install it on his work computer but they let us install unknown software.

I hope in the future you can also have it in the Microsoft store or with your certificate, much success!

## Describe the solution you'd like
Apply for a Windows license or certification in the future

## Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/68222436/196019008-6c1d1f3e-27c2-4e8d-bfea-4d4e0d5d4831.png)

**Comment by panekj** [comment] 2022-10-16 08:35
Duplicate of #1526

**Closed by panekj** 2022-10-16 08:35 UTC
Labels: C-feature
