### ISSUE TITLE
hay I'm noticing the vim support lacks alot of vim keys I'd like to work on that myself #700

### ISSUE THREAD

**Issue by rzksobhy27** [lapce/lapce#1757] opened 2022-11-26 10:20 UTC
what I'm planning to do is text objects
for example, paragraphs detecting the begging and the end of the current paragraph
this will for well with keymaps like "d i p" for deleting the current paragraph and '}' or '{' for going to the begging or the end of the begging of the paragraph

**Comment by panekj** [comment] 2022-11-26 14:10
Duplicate of #700

**Closed by panekj** 2022-11-26 14:10 UTC
Labels: C-feature
