### ISSUE TITLE
Add code folding

### ISSUE THREAD

**Issue by hakro** [lapce/lapce#2214] opened 2023-03-05 22:23 UTC
Hi !

It would be great to be able to fold function, methods, classes ..., to simplify code readability in the main editor : 

![2023-03-05_23-21](https://user-images.githubusercontent.com/3624853/222989236-e61cb9d6-7a62-435c-82f4-5866a8d90bd6.png)

Thx !

**Comment by panekj** [comment] 2023-03-05 22:26
Duplicate of https://github.com/lapce/lapce/issues/749

**Closed by panekj** 2023-03-05 22:26 UTC
Labels: C-feature

**Comment by hakro** [comment] 2023-03-05 22:44
Sorry for the noise, I did do a search of the open issues, but somehow I missed 749
Thank you :)
