### ISSUE TITLE
Changing workspaces at BSPWM

### ISSUE THREAD

**Issue by MedzikUser** [lapce/lapce#499] opened 2022-05-13 14:56 UTC
When changing workspace in bspwm (Super + Number), the editor adds a number to the open file. I will add that when I am for example on workspace 6 and I click Super + 6, the editor does not capture the number.

Version: v0.1.0

*The video has a strange resolution because I have a 21:9 monitor and the video is recorded in 16:9*

[video](https://user-images.githubusercontent.com/87065584/168310532-0c5a9eb1-0e64-4d39-bc23-a1edd6912ae7.mp4)

**Comment by bugadani** [comment] 2022-05-13 16:59
I think this is a duplicate of https://github.com/lapce/lapce/issues/250

**Closed by bugadani** 2022-05-13 16:59 UTC
Labels: C-bug, duplicate, A-editor
