### ISSUE TITLE
Extension README's do not support text selection via touchpad on macOS

### ISSUE THREAD

**Issue by scottjmaddox** [lapce/lapce#3050] opened 2024-03-08 01:05 UTC
## Lapce Version

Version 0.3.1 (1)

## System information

macOS 14.1.2 (23B92)

## Describe the bug

The README's displayed when you select an extension do not support text selection via touchpad on macOS (I haven't tried with a mouse, maybe that works). Since they often include command for installing a language server, this makes it significantly more difficult to follow the instructions.

## Additional information

Similar to https://github.com/lapce/lapce/issues/3049

If this is touchpad specific, maybe touch event handlers aren't registered?

**Comment by panekj** [comment] 2024-03-08 02:00
Duplicate of https://github.com/lapce/lapce/issues/2306

**Closed by panekj** 2024-03-08 02:00 UTC
Labels: C-bug
