### ISSUE TITLE
[Feature Request] Hide `.DS_Store` on macOS

### ISSUE THREAD

**Issue by zyxkad** [lapce/lapce#1113] opened 2022-09-09 21:32 UTC
## Is your feature request related to a problem? Please describe.

I want to hide `.DS_Store`/`.git` on macOS, these files are not useful for normal user and they are ugly

## Describe the solution you'd like

Just hide it, or you can give an option to users for hide it or not

## Additional context

<img width="248" alt="Screen Shot 2022-09-09 at 3 31 45 PM" src="https://user-images.githubusercontent.com/91082411/189448761-4475ff36-b67d-4ec6-8f86-622ae2c309fc.png">

**Comment by panekj** [comment] 2022-09-09 21:33
Duplicate of https://github.com/lapce/lapce/issues/811

**Closed by panekj** 2022-09-09 21:33 UTC
