### ISSUE TITLE
WASI docs

### ISSUE THREAD

**Issue by joaquinicolas** [lapce/lapce#1913] opened 2023-01-03 01:50 UTC
## Lapce Version

nightly

## System information

Manjaro
## Describe the bug
I'm go developer who want to create an extensions which calls Tabnine API. 
I need some additional information about how to create plugin with WASI

**Comment by panekj** [comment] 2023-01-03 14:11
duplicate of #123

**Closed by panekj** 2023-01-03 14:11 UTC
Labels: C-bug, A-documentation, A-plugins
