### ISSUE TITLE
I think there is a bug in version 0.2.3 the theme colors don't change. 

### ISSUE THREAD

**Issue by joaocarvalhoopen** [lapce/lapce#1688] opened 2022-11-11 14:49 UTC
Hello,

I have currently the DARK+ theme but I would like to change the the white color to a green one, but I cannot save what I edit in the settings, it simply doesn't change the color code that I modify.

Is that feature working correctly?

I use Linux Fedora with appimage.

Best regards,
João

**Comment by panekj** [comment] 2022-11-11 14:51
Duplicate of #1596

**Closed by panekj** 2022-11-11 14:51 UTC
Labels: C-feature
