### ISSUE TITLE
Manually select file encoding, inline mode and end line characters

### ISSUE THREAD

**Issue by Killercat103** [lapce/lapce#1973] opened 2023-01-12 14:30 UTC
I wish to be able to see and configure the inline mode, file encoding and end of line characters to an open file.
This is both useful for not having to set these options manually with the use of a separate editor. It can also prevent incompatibility issues. (Such as Linux bash files not accepting CRLF line ending)

Setting a default for these options globally or specifically to a file type would also be convenient. 

Screenshot of vscodium (Visual Studio Code):
![image](https://user-images.githubusercontent.com/75360760/212091896-eae2d034-d255-4bae-a771-2177216a3ff4.png)

**Comment by panekj** [comment] 2023-12-27 03:17
Duplicate of #870, #1627

**Closed by panekj** 2023-12-27 03:17 UTC
Labels: C-feature, A-ui, A-editor
