### ISSUE TITLE
Invisible font

### ISSUE THREAD

**Issue by Prince-Stolas** [lapce/lapce#3377] opened 2024-07-19 16:07 UTC
## Lapce Version
0.4.0

## System information
OpenSUSE Tumbleweed 64bit
Linux kernel 6.9.7

## Describe the bug
When opening the editor every bit of text in the UI is invisible, except for the terminal and editing part it self.
I tried opening the settings file like in sublime text (Ctrl+Shift+P then typing "settings") in hopes I could fix something there and they displayed fine.
Any text other than that and the line numbers doesn't show up whatsoever.

## Additional information
![img](https://github.com/user-attachments/assets/88fab1d4-b001-467b-8c08-a33f2673f7b4)

**Comment by panekj** [comment] 2024-07-19 16:11
Duplicate of https://github.com/lapce/lapce/issues/3347

**Comment by panekj** [comment] 2024-07-19 16:11
You can use nightly release since that includes built-in fonts which should render UI.

**Closed by panekj** 2024-07-19 16:11 UTC
Labels: C-bug
