### ISSUE TITLE
Invoking `lapce` in command-line without arguments

### ISSUE THREAD

**Issue by Sir-Photch** [lapce/lapce#1170] opened 2022-09-12 09:15 UTC
## Is your feature request related to a problem? Please describe.

So currently, when lapce is started from the command line, it does not capture the current working directory and just launches the editor, blocking the terminal it was started from.

## Describe the solution you'd like

vscode / codium do not elicit this behaviour. For this to be possible currently, one has to use
```console
$ lapce . &
```
Maybe this can be set as the default behaviour?

**Comment by panekj** [comment] 2022-09-12 09:17
VSCode doesn't open current workdir either and blocking terminal is duplicate of #1169

**Closed by panekj** 2022-09-12 09:17 UTC
