### ISSUE TITLE
Cursor is Pointer instead of Caret after closing Settings

### ISSUE THREAD

**Issue by midyHamdoun** [lapce/lapce#113] opened 2022-03-11 14:34 UTC
Steps to reproduce:
1. Open file to edit
2. Open settings (Click gear icon)
3. Close settings
4. Hover cursor on the text editor. It starts changing between Pointer and Caret really fast

OS: Windows 10

**Comment by vitalyster** [comment] 2022-03-17 11:46
Same for me on macOS

**Comment by bugadani** [comment] 2022-04-03 12:38
Thanks for reporting this issue!

I can't reproduce it on Windows 11. Could you please check if this still exists?

**Comment by bugadani** [comment] 2022-04-19 17:20
I think #410 should have fixed this so I'm closing this ticket, but feel free to reopen if you experience this issue in the next release.

**Closed by bugadani** 2022-04-19 17:20 UTC
Labels: C-bug, needs-more-info, A-ui
