### ISSUE TITLE
Folders empty, terminal doesn't work, plugin installation doesn't work on Mac M1

### ISSUE THREAD

**Issue by yerlaser** [lapce/lapce#3064] opened 2024-03-11 21:34 UTC
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by panekj** [comment] 2024-03-11 21:38
Duplicate of https://github.com/lapce/lapce/issues/2936

**Closed by panekj** 2024-03-11 21:38 UTC
Labels: C-bug
