### ISSUE TITLE
Thin letter i using JetBrains Mono

### ISSUE THREAD

**Issue by jrood** [lapce/lapce#2161] opened 2023-02-16 19:44 UTC
## Lapce Version

0.2.5

## System information

OSX Ventura 13.0.1

## Describe the bug

The letter `i` is weirdly thin using JetBrains Mono

## Additional information

<img width="290" alt="Screenshot 2023-02-16 at 1 39 16 PM" src="https://user-images.githubusercontent.com/6615558/219470111-79104cf0-19f9-4521-a918-1a5292376d72.png">

For reference, it looks correct in VS Code:
<img width="287" alt="Screenshot 2023-02-16 at 1 39 58 PM" src="https://user-images.githubusercontent.com/6615558/219470199-424a88f0-783f-4540-a8a3-f37ebe07cfc6.png">

**Comment by panekj** [comment] 2023-02-16 19:44
duplicate of https://github.com/lapce/lapce/issues/1487

**Closed by panekj** 2023-02-16 19:44 UTC
Labels: C-bug
