### ISSUE TITLE
Can't resize

### ISSUE THREAD

**Issue by Debdut** [lapce/lapce#31] opened 2021-12-14 23:29 UTC
```
version: 0.0.2
os: Monterey 12.1
```

When I resize or try to make it full screen, Lapce doesn't render correctly and freezes.
<img width="912" alt="Screen Shot 2021-12-15 at 4 55 34 AM" src="https://user-images.githubusercontent.com/7561070/146095701-74a3704b-d0b0-4508-8148-422ffd37855a.png">

**Comment by domesticmouse** [comment] 2021-12-14 23:31
duplicate of #20

**Comment by maks** [comment] 2021-12-15 02:57
I seem to be seeing something simliar on LInux too, but I'll add my observations into #20

**Comment by dzhou121** [comment] 2021-12-15 09:03
Should be fixed by the latest release. https://github.com/lapce/lapce/releases/tag/v0.0.3

**Closed** 2021-12-22 18:02 UTC
