### ISSUE TITLE
Open folder in WSL not working

### ISSUE THREAD

**Issue by derpy-zombie** [lapce/lapce#2979] opened 2024-02-16 09:05 UTC
## Lapce Version

nightly-4595173

## System information

Windows 11 (With Arch linux in WSL)

## Describe the bug
While connected to WSL the "Open Folder" button (both from the search bar and from File > Open Folder) does not work.
It works fine when on Windows.
I think its just that there is no GUI way of getting into a file explorer to select the folder?

I really like Lapce and use it in my linux installation but I need this feature to use it at my office.

**Comment by panekj** [comment] 2024-02-19 00:19
Duplicate of https://github.com/lapce/lapce/issues/2417
Remote file picker has not been yet reimplemented after switching to Floem
You can open a directory with lapce <path> in terminal

**Closed by panekj** 2024-02-19 00:19 UTC
Labels: C-bug
