### ISSUE TITLE
Failing to input anything to middle-top text area

### ISSUE THREAD

**Issue by VitalyyBezuglyj** [lapce/lapce#2917] opened 2024-01-12 14:22 UTC
## Lapce Version

v.0.3.1

## System information

Fedora 39 Workstation

## Describe the bug
Functionality related to typing in the text area in the middle at the top (e.g. searching for a file in an open directory, ssh connection) is not available because the text area does not allow you to type anything.

You click on it (or select ssh connection from the menu), a drop-down list appears, but it doesn't respond to any keyboard presses. 
But all other text areas work fine - main editor, settings search, Ctrl-F search, etc.

## Additional information

Filesearch:
![image](https://github.com/lapce/lapce/assets/36605305/aa24c128-10a5-494e-ba42-5392ab9e47ca)

ssh-connection:
![image](https://github.com/lapce/lapce/assets/36605305/ec9b5ae2-5df0-471d-8f86-025a6237298a)

This fails equally for an executable from a .tar.gz archive, or when installed via Flatpak

**Comment by tascord** [comment] 2024-01-14 22:21
+1 on Fedora 38 in Sway/GNOME. Will note that using tab to escape focus of the box, and then shift+tab to return allows typing for some reason.

**Comment by VitalyyBezuglyj** [comment] 2024-01-15 07:22
@tascord Unexpectedly, thank you!

**Comment by Haskellered** [comment] 2024-01-20 19:09
Appears to be the same issue as https://github.com/lapce/lapce/issues/2857

**Comment by panekj** [comment] 2024-05-14 21:23
Duplicate of https://github.com/lapce/lapce/issues/2857

**Closed by panekj** 2024-05-14 21:23 UTC
Labels: C-bug
