### ISSUE TITLE
MacOS text in terminal is not selectable

### ISSUE THREAD

**Issue by ranger-ross** [lapce/lapce#1259] opened 2022-09-18 10:21 UTC
## Is your feature request related to a problem? Please describe.

When using Lapce for web development, when i start a webserver from my terminal, many tools will print the url where the server is running. The problem is that I cannot click the link from the terminal or even select the text to copy and paste.

This could also be a problem for debugging when some langauges/tools will output links for documentation for warnings/errors.

## Describe the solution you'd like.

Make the terminal output selectable so that I can copy/paste from the terminal and text clickable if a link is detected. VSCode has a great implementation for this

**Comment by ranger-ross** [comment] 2022-09-18 11:00
I cloned the project and built from source on MacOS (Apple Silicon M1) and I see that this features is actually implemented already and works when built from source locally.

 The issue seems to happen when installing via the .dmg file.

I will update this issue from a feature request to a bug

**Comment by panekj** [comment] 2022-09-18 11:01
> Make the terminal output selectable so that I can copy/paste from

Duplicate of https://github.com/lapce/lapce/issues/871

**Closed** 2022-09-18 11:02 UTC
Labels: C-feature
