### ISSUE TITLE
Visual Bug with Lapce

### ISSUE THREAD

**Issue by UrNightmaree** [lapce/lapce#1254] opened 2022-09-17 23:39 UTC
## Lapce Version
Current Lapce Version: 0.2.0

## System information
OS: Windows 10
Version: 21H1

## Describe the bug
Lapce having visual bug after installing VCRedist. Like the X and Y of UI position is going out of screen.

## Additional information
Screenshot:
![image](https://user-images.githubusercontent.com/71205197/190879729-8a9c5089-a297-474a-a89e-3a0793863d8f.png)

**Comment by panekj** [comment] 2022-09-17 23:41
duplicate of #1083

**Closed** 2022-09-18 03:49 UTC
Labels: C-bug
