### ISSUE TITLE
access docker containers.

### ISSUE THREAD

**Issue by maki-07061210** [lapce/lapce#2789] opened 2023-11-16 04:10 UTC
## Is your feature request related to a problem? Please describe.

I can't develop because all development environments are docker.

## Describe the solution you'd like

I want "dev containers" of "visual studio code" in this editor as well.

**Comment by panekj** [comment] 2023-11-16 08:03
Duplicate of https://github.com/lapce/lapce/issues/1481

**Closed by panekj** 2023-11-16 08:03 UTC
Labels: C-feature
