### ISSUE TITLE
ArchLinux/Wayland/US-intl: doesn't work to enter "digraphs"

### ISSUE THREAD

**Issue by vromanocarepay** [lapce/lapce#2490] opened 2023-06-27 16:41 UTC
## Lapce Version

extra/lapce 0.2.8-1

## System information

Kernel Version : 6.3.9.zen1-1
Plasma Version : 5.27.6-1
KDE Version : 23.04.2-1
Frameworks Version : 5.107.0-1
Qt5 Version : 5.15.10+kde+r9-1
Wayland Version : 1.22.0-1
XOrg/Wayland Version : 23.1.2-1
Mesa Version : 23.1.3-1
LibVA Version : 2.18.0-1
VDPAU Version : 1.5-1

Kayboard layout: English (US, alt.intl.)

## Describe the bug
In order to enter certain character like " or ' or ^ , I usually hit it and the hit a SPACE.
If instead of SPACE I hit, for example, a vowel like "a" after ' I get "à" .
This is the intended behavior I can see in browsers, terminal application and other "code" editors.

In LAPCE, instead, I don't get nothing.

## Additional information

n/a

**Comment by panekj** [comment] 2023-06-27 16:42
duplicate of #1094

**Closed by panekj** 2023-06-27 16:42 UTC
Labels: C-bug
