### ISSUE TITLE
cargo.toml failed parce

### ISSUE THREAD

**Issue by dronov-dmitry** [lapce/lapce#1346] opened 2022-09-25 11:06 UTC
Whet try to build at linux mint - it show me error:

"""
failed to parse manifest at `/home/Lapce/lapce-core/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
"""

**Comment by panekj** [comment] 2022-09-25 11:06
You need at least Rust 1.62

**Comment by panekj** [comment] 2022-09-25 11:07
Duplicate of #1095

**Closed by panekj** 2022-09-25 11:06 UTC
Labels: C-bug
