### ISSUE TITLE
Image file preview

### ISSUE THREAD

**Issue by nick-1666** [lapce/lapce#2047] opened 2023-01-22 15:00 UTC
VsCode has a nice feature where it will display images and svgs when clicked on.
![image](https://user-images.githubusercontent.com/67550680/213922699-4fb98dd3-2d78-467b-83ea-eb5cf1755300.png)

**Comment by panekj** [comment] 2023-01-22 15:02
Duplicate of #902

**Closed by panekj** 2023-01-22 15:02 UTC
Labels: C-feature
