### ISSUE TITLE
App crashes on opening folder

### ISSUE THREAD

**Issue by kwiat1990** [lapce/lapce#2242] opened 2023-03-13 10:01 UTC
## Lapce Version

`0.2.6`

## System information

`MacOS Ventura 13.2`

## Describe the bug
Open `lapce` app and then in menu click `file -> open folder`. In 8 out of 10 tries if a rust project will be selected, the app crashes and OS show following information:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/19494075/224669015-583017d3-c5b6-4055-a52b-25126d24c276.png">

I have reinstalled the app but it didn't help.

**Comment by panekj** [comment] 2023-03-13 10:03
Duplicate of #2200

**Closed by panekj** 2023-03-13 10:03 UTC
Labels: C-bug
