### ISSUE TITLE
Lapce not running on dell e6500 running arch linux

### ISSUE THREAD

**Issue by Michaelin007** [lapce/lapce#1156] opened 2022-09-11 17:15 UTC
## Lapce Version 0.2.0

Anytime I launch lapce from my terminal, I get this error: thread 'main' panicked at '0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
', /build/.cargo/git/checkouts/piet-wgpu-913b036275d2afb6/f863b3e/src/pipeline.rs:89:13

**Comment by ghishadow** [comment] 2022-09-11 17:16
duplicate of https://github.com/lapce/lapce/issues/1062

**Comment by panekj** [comment] 2022-09-11 17:16
duplicate of #1108

**Closed** 2022-09-11 17:16 UTC
