### ISSUE TITLE
Font smoothing looks bad

### ISSUE THREAD

**Issue by sdgoihew** [lapce/lapce#2138] opened 2023-02-12 04:00 UTC
![Screenshot_3](https://user-images.githubusercontent.com/115432842/218292302-1075e5b0-451d-4f17-bf88-41d7796a2e2f.png)

**Comment by kythyria** [comment] 2023-02-13 19:45
I'm guessing you have a BGR monitor, in which case this is likely a duplicate of #1334.

**Comment by sdgoihew** [comment] 2023-02-13 22:18
Closed as duplicate

**Closed** 2023-02-13 22:18 UTC
Labels: C-feature, A-font
