### ISSUE TITLE
Current extension-based syntax highlighting doesn't work for some cases

### ISSUE THREAD

**Issue by AlexRamallo** [lapce/lapce#1928] opened 2023-01-06 13:11 UTC
## Lapce Version

Built from latest master branch (a49e354e)

## System information

Fedora 37

## Describe the bug

`lapce-core/language.rs` assigns file extensions to languages, which is how the syntax highlighting gets activated. This doesn't work for standard file names that need a particular syntax highlighting, but don't use a file extension.

In my case, that's the [waf build system](https://waf.io), which uses files called "wscript" (not "<whatever>.wscript") for build definitions. wscript files should use Python syntax highlighting, but there's no way to tell Lapce to always use Python highlighting for them.

## Additional information

I tried adding "wscript" to the extensions list for Python, but that only works if the file ends with ".wscript"

**Comment by panekj** [comment] 2023-01-06 13:12
Duplicate of #1873

**Closed by panekj** 2023-01-06 13:12 UTC
Labels: C-bug
