### ISSUE TITLE
Opening any directory crashes Lapce

### ISSUE THREAD

**Issue by jrasanen** [lapce/lapce#2226] opened 2023-03-10 13:07 UTC
## Lapce Version

0.2.6

## System information

* computer model: Apple M1 Pro
* macOS version: 13.2.1
* macOS hostname: `Rasanen's-MacBook`
* macOS username: `jussi.rasanen`

## Describe the bug

1. Download Lapce using Homebrew
2. Open Lapce.app
3. Open any directory

### Video to reproduce the issue

https://user-images.githubusercontent.com/13303/224323488-c7d4e332-326b-4094-a5bc-7bbbdbf946b7.mp4

### Logs

```
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: g f
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: o
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: /
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: :
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+g
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: g g
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: h
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: j
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: k
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: l
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: a
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+a
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: i
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: u
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+r
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+i
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+o
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+n
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: g d
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: g h
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: p
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+p
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+j
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: y
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: x
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+p
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: s
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: c
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+s
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: c c
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: c w
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: c e
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+i
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: o
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: 0
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ^
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: $
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: w
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: e
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: b
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+o
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+e
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+y
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+u
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+d
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: z z
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: z t
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: z b
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: d
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: f
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+f
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ;
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: d
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: >
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: <
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: y
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: *
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: n
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+n
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: %
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ] )
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: [ (
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ] }
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: [ {
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: v
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+v
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+v
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w l
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w h
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w j
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w k
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w s
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w v
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w c
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w x
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: space
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: >
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: <
[2023-03-10][15:01:58][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+c
[2023-03-10][15:01:58][lapce_data::keypress][ERROR] Failed to load from "/Users/jussi.rasanen/Library/Application Support/dev.lapce.Lapce-Stable/keymaps.toml": no keymaps
[2023-03-10][15:01:58][reqwest::connect][DEBUG] starting new connection: https://plugins.lapce.dev/
[2023-03-10][15:01:58][hyper::client::connect::dns][DEBUG] resolving host="plugins.lapce.dev"
[2023-03-10][15:01:58][lapce_proxy::terminal][WARN] setlocale(en_FI.UTF-8) failed, fall back to en_US.UTF-8
[2023-03-10][15:01:58][reqwest::connect][DEBUG] starting new connection: https://api.github.com/
[2023-03-10][15:01:58][hyper::client::connect::dns][DEBUG] resolving host="api.github.com"
[2023-03-10][15:01:58][hyper::client::connect::http][DEBUG] connecting to 140.82.121.5:443
[2023-03-10][15:01:58][druid::localization][DEBUG] available locales [], current en-FI
[2023-03-10][15:01:58][druid::localization][DEBUG] resolved: [en-US]
[2023-03-10][15:01:58][hyper::client::connect::http][DEBUG] connecting to 104.26.4.224:443
[2023-03-10][15:01:58][hyper::client::connect::http][DEBUG] connected to 140.82.121.5:443
[2023-03-10][15:01:58][hyper::client::connect::http][DEBUG] connected to 104.26.4.224:443
[2023-03-10][15:01:58][alacritty_terminal::term][DEBUG] New num_cols is 64 and num_lines is 10
[2023-03-10][15:01:59][hyper::client::pool][DEBUG] pooling idle connection for ("https", api.github.com)
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3''7'],['R''e''m''o''t''e''H''o''s''t''=''j''u''s''s''i''.''r''a''s''a''n''e''n''@''R''a''s''a''n''e''n''\'''s''-''M''a''c''B''o''o''k'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3''7'],['C''u''r''r''e''n''t''D''i''r''=''/''U''s''e''r''s''/''j''u''s''s''i''.''r''a''s''a''n''e''n'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3''7'],['S''h''e''l''l''I''n''t''e''g''r''a''t''i''o''n''V''e''r''s''i''o''n''=''1''3'],['s''h''e''l''l''=''z''s''h'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1'],['~'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3'],['D'],['0'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3''7'],['R''e''m''o''t''e''H''o''s''t''=''j''u''s''s''i''.''r''a''s''a''n''e''n''@''R''a''s''a''n''e''n''\'''s''-''M''a''c''B''o''o''k'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3''7'],['C''u''r''r''e''n''t''D''i''r''=''/''U''s''e''r''s''/''j''u''s''s''i''.''r''a''s''a''n''e''n'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3'],['A'],] at line 963
[2023-03-10][15:01:59][alacritty_terminal::ansi][DEBUG] [unhandled osc_dispatch]: [['1''3''3'],['B'],] at line 963
[2023-03-10][15:01:59][hyper::client::pool][DEBUG] pooling idle connection for ("https", plugins.lapce.dev)
[2023-03-10][15:01:59][reqwest::connect][DEBUG] starting new connection: https://plugins.lapce.dev/
[2023-03-10][15:01:59][hyper::client::connect::dns][DEBUG] resolving host="plugins.lapce.dev"
[2023-03-10][15:01:59][hyper::client::connect::http][DEBUG] connecting to 104.26.4.224:443
[2023-03-10][15:01:59][hyper::client::connect::http][DEBUG] connected to 104.26.4.224:443
[2023-03-10][15:02:00][hyper::client::pool][DEBUG] pooling idle connection for ("https", plugins.lapce.dev)
[2023-03-10][15:02:28][reqwest::connect][DEBUG] starting new connection: https://plugins.lapce.dev/
```

**Comment by panekj** [comment] 2023-03-10 13:08
Duplicate of #2200

**Closed by panekj** 2023-03-10 13:08 UTC
Labels: C-bug
