### ISSUE TITLE
Portable app icon does not appear on Windows taskbar

### ISSUE THREAD

**Issue by tech189** [lapce/lapce#162] opened 2022-03-18 12:07 UTC
![image](https://user-images.githubusercontent.com/10728085/158999930-bc6325ff-4f64-4b43-b334-9b42d8b16448.png)
On the left is the portable version while the right is the `.msi` installer version.

It's also not included in the file so shortcuts display the same placeholder:
```
The file ...\lapce.exe contains no icons.

Choose an icon from the list or specify a different file.

[OK]
```

**Comment by bugadani** [comment] 2022-04-03 09:45
Hi and thanks for reporting! I believe this is a duplicate of #48 so I'm closing this issue in favour of that. However, feel free to reopen if you disaggree.

**Closed by bugadani** 2022-04-03 09:45 UTC
Labels: C-bug, duplicate, A-ui
