### ISSUE TITLE
Linker fail on linux

### ISSUE THREAD

**Issue by omartijn** [lapce/lapce#11] opened 2021-12-14 09:30 UTC
During the final link step, the following error occurs:

      = note: /usr/bin/ld: cannot find -lxcb-shape
              /usr/bin/ld: cannot find -lxcb-xfixes
              clang: error: linker command failed with exit code 1 (use -v to see invocation)

On Debian/Ubuntu, this is fixed installing the packages `libxcb-xfixes0-dev` and `libxcb-shape0-dev`. Coming from C++ this is strange to me (you'd imagine you need the headers to _compile_, not to link). Anyway, the error message is unclear.

**Comment by bjorn3** [comment] 2021-12-14 10:40
> Coming from C++ this is strange to me (you'd imagine you need the headers to compile, not to link).

The -dev packages include not just headers but also the symlinks necessary for the linker to find libraries.

> Anyway, the error message is unclear.

Maybe rustc could try to give a somewhat better error message when it finds this kind of linker error, but it would be impossible to always correctly guess the right package name for a library especially across different distros.

**Comment by eldar** [comment] 2021-12-14 12:11
I am on Ubuntu 20.04 and needed to install the following packages `libxcb-shape0-dev libxcb-xfixes0-dev libxcb-render0-dev libxkbcommon-dev`. Perhaps, it is worth adding to the README.

**Comment by bugadani** [comment] 2022-04-03 06:57
Hi and thanks for reporting this issue! I'm going to close this as a duplicate of #3 for now, as I think this is more related to unclear build instructions than any other technical problem. Other than that, general linker errors, and the clarity of compiler/linker error messages are I think out of scope for this project.

If you have a definite set of packages that you need to install on your OS, feel free to open a PR that adds it to the readme, and reference #3 in that PR. Thank you!

**Closed by bugadani** 2022-04-03 06:57 UTC
Labels: question, P-linux, A-documentation
