### ISSUE TITLE
v0.3.0 does not start on NixOS

### ISSUE THREAD

**Issue by jansol** [lapce/lapce#2752] opened 2023-11-03 13:56 UTC
## Lapce Version
0.3.0

## System information

NixOS unstable

## Describe the bug
Silent crash by default, when launched with `-w` I get a backtrace that points to a font issue:

```console
$ result/bin/lapce -w
2023-11-03T13:47:48.969029Z ERROR lapce_app::keypress: Failed to load from "/home/user/.config/lapce-nightly/keymaps.toml": no keymaps
thread 'main' panicked at 'no default font found', /build/cargo-vendor-dir/cosmic-text-0.7.0/src/buffer_line.rs:192:41
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: cosmic_text::buffer_line::TextLayoutLine::shape
   4: cosmic_text::buffer_line::TextLayoutLine::layout
   5: cosmic_text::buffer::TextLayout::shape_until
   6: cosmic_text::buffer::TextLayout::set_text
   7: cosmic_text::buffer::TextLayout::new
   8: floem_reactive::signal::ReadSignal<T>::with_untracked
   9: <floem_reactive::effect::Effect<T,F> as floem_reactive::effect::EffectTrait>::run
  10: floem_reactive::scope::with_scope
  11: floem_reactive::effect::run_effect
  12: floem_reactive::effect::create_effect
  13: floem_reactive::scope::with_scope
  14: lapce_app::window_tab::WindowTabData::new
  15: lapce_app::window::WindowData::new
  16: lapce_app::app::AppData::app_view
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  18: floem_reactive::scope::with_scope
  19: floem::window_handle::WindowHandle::new
  20: floem::app_handle::ApplicationHandle::new_window
  21: floem::app::Application::window
  22: lapce_app::app::launch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Additional information

pop-os/cosmic-text#167 is a likely culprit

**Comment by dzhou121** [comment] 2023-11-03 14:15
Can you please try the nightly version which just make "fontconfig" enabled on fontdb

**Comment by panekj** [comment] 2023-11-04 06:15
Duplicate of https://github.com/lapce/lapce/issues/2748

**Closed by panekj** 2023-11-04 06:15 UTC
Labels: C-bug, C-crash 💥, A-font
