### ISSUE TITLE
Build failed on Windows 10 with rust version 1.64 stable

### ISSUE THREAD

**Issue by cqlangyi** [lapce/lapce#1328] opened 2022-09-23 15:19 UTC
## Lapce Version

commit 7b981773b20762e0211ce77c51004afba7c48e32

## System information

windows 10

## Describe the bug
error: failed to run custom build command for `tree-sitter-svelte v0.10.2 (https://github.com/Himujjal/tree-sitter-svelte?branch=master#52e122ae)`

Caused by:
  process didn't exit successfully: `D:\projects\rust\lapce\target\release\build\tree-sitter-svelte-c46ade77440d706d\build-script-build` (exit code: 1)
  --- stderr

  error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "src" "-W4" "-FoD:\\projects\\rust\\lapce\\target\\release\\build\\tree-sitter-svelte-5b59724ab4831aec\\out\\src\\scanner.o" "-c" "src\\scanner.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

any help would be appreciated.

**Comment by panekj** [comment] 2022-09-23 15:23
Duplicate of https://github.com/lapce/lapce/issues/671

**Closed by panekj** 2022-09-23 15:23 UTC
Labels: C-bug
