### ISSUE TITLE
Support for github copilot

### ISSUE THREAD

**Issue by chiboycalix** [lapce/lapce#2611] opened 2023-09-12 14:37 UTC
## Is your feature request related to a problem? Please describe.
I am planning on moving over to Lapce from vs code but I don't have access to my GitHub Copilot subscription

## Describe the solution you'd like

> - Ability to use GitHub copilot

**Comment by panekj** [comment] 2023-09-12 14:38
Duplicate of https://github.com/lapce/lapce/issues/1081

**Closed by panekj** 2023-09-12 14:38 UTC
Labels: C-feature
