### ISSUE TITLE
Add search and replace function

### ISSUE THREAD

**Issue by ignorantshr** [lapce/lapce#2414] opened 2023-05-29 08:37 UTC
## Is your feature request related to a problem? Please describe.

nothing

## Describe the solution you'd like

Add search and replace function, I can't imagine that lapce doesn't have this function

## Describe alternatives you've considered

nothing

## Additional context

nothing

**Comment by panekj** [comment] 2023-05-29 08:38
Duplicate of #1223

**Closed by panekj** 2023-05-29 08:38 UTC
Labels: C-feature
