### ISSUE TITLE
lapce- entry point is not found

### ISSUE THREAD

**Issue by dove88** [lapce/lapce#1144] opened 2022-09-11 12:43 UTC
![IMG_20220911_181237.jpg](https://user-images.githubusercontent.com/85496354/189528146-86c4d809-e921-4c31-bb98-617bfd849304.jpg)

Please check the bug report in the photo attached.

**Comment by sebastian-de** [comment] 2022-09-11 13:06
Duplicate of https://github.com/lapce/lapce/issues/1137

**Closed** 2022-09-11 14:51 UTC

**Comment by dove88** [comment] 2022-09-11 16:46
I have windows 10,

**Comment by panekj** [comment] 2022-09-11 16:47
You need at least `Windows 10 October 2018 Update (version 1809)`

**Comment by dove88** [comment] 2022-09-13 18:09
Ok
