### ISSUE TITLE
Please add the Line Wrapping feature mode for TXT and MarkDown files.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [lapce/lapce#1677] opened 2022-11-10 14:50 UTC
Hello,

great editor!

Please consider adding Line Wrapping feature mode to txt and MarkDown.

It should be easy to enable or disable the feature for a file type.

Best regards,
João

**Comment by panekj** [comment] 2022-11-10 14:51
Duplicate of #945

**Closed by panekj** 2022-11-10 14:51 UTC
Labels: C-feature
