### ISSUE TITLE
[Crash] on startup on MacOS Mojave

### ISSUE THREAD

**Issue by MrGcGamer** [lapce/lapce#526] opened 2022-05-20 10:43 UTC
Lapce crashes on start up.

Error log can be found here:
https://pastebin.com/B3h40Hgm

I am running MacOs Mojave (10.14.6) on a MacBookPro 2011 (exact specs can be found in the crash report)

**Comment by panekj** [comment] 2022-09-30 15:09
duplicate of https://github.com/lapce/lapce/issues/889

**Closed by panekj** 2022-09-30 15:09 UTC
Labels: P-macos, C-crash 💥
