### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Frusasoft-frusadev** [lapce/lapce#1765] opened 2022-11-30 14:43 UTC
I'm trying to run the executable file but it does not launch so tries lapce -w and it says " _Segmentation_ fault (core dumped)_"

I'm on Zorin OS 16.1
Intel Pentium(R) Dual-Core CPU E5800 @ 3.20GHz × 2
4gb ram
 kernel version: 5.15.0-46-generic

**Comment by Arjun31415** [comment] 2022-11-30 14:54
What is the extension of the file?

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:33
I'm on linux so there is not extension

**Comment by TudbuT** [comment] 2022-11-30 16:35
> What is the extension/language of the file?

does not matter, the file runs, because otherwise there would be no difference between having -w and not having it

**Comment by TudbuT** [comment] 2022-11-30 16:37
can you share the core dump? it should be in /var/lib/systemd/coredump

**Comment by TudbuT** [comment] 2022-11-30 16:41
can you run `coredumpctl gdb` and then type `bt` and send the output? that's probably all the info needed, you don't actually have to send the full core dump in many cases

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:42
Okay

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:44
**coredumpctl gdb**/> No match found

**Comment by TudbuT** [comment] 2022-11-30 16:45
oh, you need to add an id argument after the `gdb`. you can find that in `coredumpctl list`

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:48
TIME                            PID   UID   GID SIG COREFILE  EXE
Wed 2022-11-30 16:45:40 GMT   19005  1000  1000  11 present   ~/Downloads/Lapce-linux (1)/Lapce/lapce

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:48
so i use "19005 1000 1000 11"

**Comment by panekj** [comment] 2022-11-30 16:48
Duplicate of #587

**Comment by TudbuT** [comment] 2022-11-30 16:48
the id is 19005, so you need to run `coredumpctl gdb 19005`

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:49
Okay i've found it

**Closed by panekj** 2022-11-30 16:48 UTC
Labels: C-bug

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:52
![Screenshot from 2022-11-30 16-51-10](https://user-images.githubusercontent.com/81917636/204859088-3960e9eb-2745-4e78-8f0c-78e18e03476c.png)

**Comment by TudbuT** [comment] 2022-11-30 16:53
i think you can look at the duplicate issue for the solution

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:55
Okay

**Comment by Frusasoft-frusadev** [comment] 2022-11-30 16:55
Thanks !
