### ISSUE TITLE
Quit / Exit command

### ISSUE THREAD

**Issue by cart** [lapce/lapce#681] opened 2022-06-25 20:57 UTC
It looks like there isn't a way to quit the editor via a command. I'd like to be able to close the editor using something like `ctrl + q`.

**Comment by MinusGix** [comment] 2022-06-25 21:48
I'm mildly against a default keybinding of Ctrl+Q since it makes it easy to accidentally use when you're trying to use Ctrl+Tab (next tab) or Ctrl+W (close current tab), but it would be good to at least have a command that can be bound and a workbench command for it.

**Comment by cart** [comment] 2022-06-25 22:08
Makes sense! I agree with the "`Ctrl+Q` is a bad default" assessment. I'd probably roll with "no default binding, but providing a workbench command".

**Comment by panekj** [comment] 2022-09-13 20:07
Duplicate of #234

**Closed by panekj** 2022-09-13 20:07 UTC
Labels: C-feature, A-editor
