### ISSUE TITLE
Lapce crashes on Windows

### ISSUE THREAD

**Issue by cesarblender** [lapce/lapce#1614] opened 2022-10-28 00:09 UTC
## Lapce Version

Latest (0.2.1) 10/27/2022

## System information

OS: Windows 11 64 bit
Disk: ssd 144gb/230gb
RAM: 4gb
CPU: Intel Dual-Core 2.60GHz

## Describe the bug
I've installed the program, but when I try to open, nothing happen, I've checked the task manager and it shows a new task (Lapce task) but it stops after seconds.

## Additional information

- What I've tried to solve the bug
    - I've tried reinstalling the program (doesn't work)
    - I've tried rebooting my system (doesn't work)
- Logs
```[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: o
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: /
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: :
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+g
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: g g
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: h
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: j
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: k
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: l
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: a
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+a
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: i
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: u
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+r
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+i
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+o
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+n
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: g d
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: p
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+p
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+j
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: y
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: x
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+p
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: s
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+i
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: o
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: 0
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ^
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: $
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: w
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: e
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: b
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+o
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+e
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+y
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+u
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+d
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: z z
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: z t
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: z b
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: d
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: f
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+f
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ;
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: d
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: >
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: <
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: y
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: *
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: n
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+n
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: %
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ] )
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: [ (
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ] }
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: [ {
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: v
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: shift+v
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+v
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w l
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w h
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w j
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w k
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w s
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w v
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w c
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: ctrl+w x
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: space
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: >
[2022-10-27][18:13:15][lapce_data::keypress::loader][DEBUG] Keymap ignored: <
[2022-10-27][18:13:15][lapce_data::keypress][ERROR] Failed to load from "C:\\Users\\seokk\\AppData\\Roaming\\lapce\\Lapce-Stable\\config\\keymaps.toml": no keymaps
[2022-10-27][18:13:15][reqwest::connect][DEBUG] starting new connection: https://lapce.dev/
[2022-10-27][18:13:15][hyper::client::connect::dns][DEBUG] resolving host="lapce.dev"
[2022-10-27][18:13:15][reqwest::connect][DEBUG] starting new connection: https://api.github.com/
[2022-10-27][18:13:15][hyper::client::connect::dns][DEBUG] resolving host="api.github.com"
[2022-10-27][18:13:15][druid::localization][DEBUG] available locales [], current es-VE
[2022-10-27][18:13:15][druid::localization][DEBUG] resolved: [en-US]
[2022-10-27][18:13:15][hyper::client::connect::http][DEBUG] connecting to 140.82.112.6:443
[2022-10-27][18:13:16][panic][ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(no avaible pixel format)': C:\Users\runneradmin\.cargo\git\checkouts\druid-f6980810fb848923\281fe4b\druid-shell\src\backend\windows\window.rs:843
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: git_filter_source_repo
   4: git_filter_source_repo
   5: git_filter_source_repo
   6: git_filter_source_repo
   7: git_filter_source_repo
   8: tree_sitter_bash
   9: tree_sitter_bash
  10: git_filter_source_repo
  11: git_filter_source_repo
  12: git_filter_source_repo
  13: DispatchMessageW
  14: DispatchMessageW
  15: CallNextHookEx
  16: KiUserCallbackDispatcher
  17: NtUserCreateWindowEx
  18: CreateWindowExW
  19: CreateWindowExW
  20: CreateWindowExW
  21: git_filter_source_repo
  22: git_filter_source_repo
  23: <unknown>
  24: <unknown>
  25: tree_sitter_bash
  26: BaseThreadInitThunk
  27: RtlUserThreadStart

```
- theories about what might be going wrong
    - Reading the logs, I found that the program looks for a file in C:\Users\USER\AppData\Roaming\lapce\Lapce-Stable\config\keymaps.toml but it shows an error. Idk what I can do.

**Comment by seokkuuu** [comment] 2022-10-28 00:11
## **NOTE**: The keymaps file in C:\Users\USER\AppData\Roaming\lapce\Lapce-Stable\config\keymaps.toml exists!!!

**Comment by adam-becker** [comment] 2022-10-28 20:59
```
[ERROR] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other(no avaible pixel format)': C:\Users\runneradmin\.cargo\git\checkouts\druid-f6980810fb848923\281fe4b\druid-shell\src\backend\windows\window.rs:843
```

Nothing to do with key bindings, everything to do with rendering on windows.

**Comment by seokkuuu** [comment] 2022-10-29 17:45
@adam-becker I have old graphics, in specific, I'm using the Pentium Dual-Core CPU integrated graphics, and it only support OpenGL 1.4 and earlier (I recently added a dll that makes support OpenGL 2.2 and erarlier and it works perfectly with programs like minecraft or unity)

I'm thinking that lapce doesn't support old graphics, like godot engine or blender :( I've tried without that dll and happens the same

**Comment by adam-becker** [comment] 2022-10-30 21:13
Duplicate of #1394 and #1286, which is also being tracked in linebender/druid#2266. Though two of the issues were caught using a VM, the underlying problem is the same.

**Comment by seokkuuu** [comment] 2022-10-30 22:28
Have planned to add support for old graphic cards, or is it not convenient at all?

**Comment by adam-becker** [comment] 2022-10-30 23:11
I'm not a maintainer, but this looks like a problem that (possibly) `druid` would have to solve.

**Comment by matresnan** [comment] 2022-11-19 03:55
https://pic5.58cdn.com.cn/nowater/webim/big/n_v2aa1c90ab76a64f00937cf6f5fbb1f185.png

Unable to open the software in Windows 7 system
software version：0.2.4

**Comment by MinusGix** [comment] 2022-11-19 04:13
> https://pic5.58cdn.com.cn/nowater/webim/big/n_v2aa1c90ab76a64f00937cf6f5fbb1f185.png
> 
> Unable to open the software in Windows 7 system software version：0.2.4

This is the wrong issue for that. https://github.com/lapce/lapce/issues/132, unfortunately Windows 7 isn't currently supported.

**Comment by panekj** [comment] 2023-12-27 03:01
Fixed since we don't use Druid anymore

**Closed by panekj** 2023-12-27 03:01 UTC
Labels: C-bug, C-crash 💥
