### ISSUE TITLE
Mac Finder: cannot open any file type with mouse

### ISSUE THREAD

**Issue by bobosola** [lapce/lapce#1929] opened 2023-01-06 14:45 UTC
## Lapce Version
0.2.5

## System information
Mac mini M1 2021
MacOS Ventura 13.0.1

## Describe the bug
Cannot open any file type in Lapce in Mac Finder using mouse > right-click > _Open With_ > _Other..._ then selecting Lapce as either the temporary or default ("Always Open With") app to open the file type. 

A macOS error dialog pops up with message "**The document xxx.yyy could not be opened. Lapce cannot open files of this type**" as per attached screenshots. This affects all file types. It seems that the only way to open files on a Mac currently is by using the File menu within Lapce, which works as expected.

## Additional information
![Screenshot 2023-01-06 at 14 35 19](https://user-images.githubusercontent.com/11035980/211033254-2f690619-38d4-4f54-9045-2f1190bcad06.png)

![Screenshot 2023-01-06 at 14 30 57](https://user-images.githubusercontent.com/11035980/211033368-7e14476a-1083-44ae-9080-c2a68abe32fb.png)

![Screenshot 2023-01-06 at 14 15 22](https://user-images.githubusercontent.com/11035980/211029575-794643e5-195b-4088-b352-23e22b390b73.png)

Also fails with .txt and all other file types.
![Screenshot 2023-01-06 at 14 06 06](https://user-images.githubusercontent.com/11035980/211028586-547430de-67a3-4209-ae25-3eaa5d601b38.png)

**Comment by panekj** [comment] 2023-01-06 14:46
Duplicate of #1430

**Closed by panekj** 2023-01-06 14:46 UTC
Labels: C-bug
