### ISSUE TITLE
thread 'main' panicked at reactive/src/read.rs:39:24: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by bf** [lapce/lapce#3601] opened 2024-12-14 21:05 UTC
## Lapce Version

0.4.2

## System information

arch linux gnome-shell wayland latest

## Describe the bug

It crashes when you drag the "terminal" tab from bottom panel to right side panel (or vice versa) .

After restart the "terminal" tab is where you dragged it (so the dragging succeed) but somehow it crashed.

## Additional information

```
 RUST_BACKTRACE=full lapce -w
thread 'main' panicked at /build/.cargo/git/checkouts/floem-69eea0a757d1e3ee/157631a/reactive/src/read.rs:39:24:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x5e0a03c4578a - <unknown>
   1:     0x5e0a025ba0eb - <unknown>
   2:     0x5e0a03c15c22 - <unknown>
   3:     0x5e0a03c4be49 - <unknown>
   4:     0x5e0a03c4b636 - <unknown>
   5:     0x5e0a03c4ca79 - <unknown>
   6:     0x5e0a03c4c16a - <unknown>
   7:     0x5e0a03c4c0f9 - <unknown>
   8:     0x5e0a03c4c0e6 - <unknown>
   9:     0x5e0a02408432 - <unknown>
  10:     0x5e0a024085cb - <unknown>
  11:     0x5e0a024089c8 - <unknown>
  12:     0x5e0a028dd11c - <unknown>
  13:     0x5e0a02c7611a - <unknown>
  14:     0x5e0a03175963 - <unknown>
  15:     0x5e0a02924ef8 - <unknown>
  16:     0x5e0a0316c9cb - <unknown>
  17:     0x5e0a0316c617 - <unknown>
  18:     0x5e0a03155e24 - <unknown>
  19:     0x5e0a0316c499 - <unknown>
  20:     0x5e0a0287ba55 - <unknown>
  21:     0x5e0a027fa2cc - <unknown>
  22:     0x5e0a027f113b - <unknown>
  23:     0x5e0a027ee944 - <unknown>
  24:     0x5e0a027c7dad - <unknown>
  25:     0x5e0a027cc210 - <unknown>
  26:     0x5e0a034218bc - <unknown>
  27:     0x5e0a024eb496 - <unknown>
  28:     0x5e0a024eb89b - <unknown>
  29:     0x76f492243e08 - <unknown>
  30:     0x76f492243ecc - __libc_start_main
  31:     0x5e0a024eaf85 - <unknown>
  32:                0x0 - <unknown

```

**Comment by panekj** [comment] 2024-12-14 21:06
Duplicate of https://github.com/lapce/lapce/issues/3338

**Closed by panekj** 2024-12-14 21:06 UTC
Labels: C-bug
