### ISSUE TITLE
Accept input on STDIN

### ISSUE THREAD

**Issue by egrieco** [lapce/lapce#1704] opened 2022-11-15 17:45 UTC
## Describe the solution you'd like

It is frequently helpful to be able to pipe output text from a command into a text editor to be able to review and edit.

As lapce is an actual program and not an Electron app, this should be relatively easy to implement.

## Describe alternatives you've considered

It is possible to create an alias in the shell to create a temporary file and then open that file in lapce, however this has a few disadvantages:

1. Temp file clutter: temp files need to be cleaned up at some point. It's better to not waste disk space unless it's necessary.
2. Information leakage: temp files may contain sensitive data. Temp file locations typically are not well secured. It's better to pipe data directly to memory and then allow the user to determine where to persist the data on disk.
3. Temp file collisions: if proper naming practices are not followed, one temp file may overwrite another leading to data loss.

**Comment by panekj** [comment] 2022-11-15 17:46
Duplicate of https://github.com/lapce/lapce/issues/1608

**Comment by egrieco** [comment] 2022-11-15 17:46
P.S. I've downloaded the lapce source and it compiles and runs successfully on my machine. I intend to add this feature if no one beats me to it, but I'm not sure when I'll get to it.

**Closed by panekj** 2022-11-15 17:46 UTC
Labels: C-feature

**Comment by egrieco** [comment] 2022-11-15 17:47
@panekj Not sure how I missed #1608, I did do several searches before posting this issue. Thanks for the catch.
