### ISSUE TITLE
Crash on opening or closing a project

### ISSUE THREAD

**Issue by eirnym** [lapce/lapce#2219] opened 2023-03-08 19:57 UTC
## Lapce Version

Lapce 0.2.6, macOS dmg downloaded from GitHub releases

## System information

macOS Monterey, MBA with M2 CPU

## Describe the bug

Crash on closing, opeining, or changing a folder with a basic Python project. 

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used
- plugins installed

Plugins installed: 
* Ayu
* Aleph
* Aura Theme
* Catppuccin
* Alabaster
* Material Icon theme
* Visual Studio Code Themes
* Tokio Night
* Rust
* Python (python-lsp-server)

<details><summary>Apple crash log</summary>
https://gist.github.com/eirnym/6403efd2e35b62679ef7ae6a04f9b0ed
</details>

**Comment by panekj** [comment] 2023-03-08 19:58
Duplicate of #2200

**Closed by panekj** 2023-03-08 19:58 UTC
Labels: C-bug
