### ISSUE TITLE
Anti-aliasing is cursed on HiDPI screens

### ISSUE THREAD

**Issue by LoganDark** [lapce/lapce#334] opened 2022-03-31 04:07 UTC
![image](https://user-images.githubusercontent.com/4723091/160974138-e15cb227-eb60-4901-804a-744b85b980fb.png)

I'm not quite sure what's going on here...

If I set the font to something else (i.e. `Input Mono`) the issue seems to lessen:

![image](https://user-images.githubusercontent.com/4723091/160974222-97ca9d71-1dec-409b-8b42-908d97e8f1d2.png)

however, text all throughout the app is still anti-aliased quite wrongly:

![image](https://user-images.githubusercontent.com/4723091/160974287-11673d4f-02ca-408c-8312-d195af0c98d3.png)

First issue, and probably the last since Lapce really doesn't seem like my type of editor. Sorry! But it's nice to see the state of desktop apps written in Rust advancing a tiny bit at least.

<details><summary>small list of first impression issues (yes I know it's a pre-alpha)</summary>

- The app looks like a weird fusion of VSCode and Atom... two of my least favorite text editors
- A lot of interactions are implemented weirdly like text being unselectable in the command palette
- wgpu still has [that stretching issue](https://github.com/gfx-rs/wgpu/issues/1168)
- font fattening / "stem darkening" is one of my least favorite things from macOS and Lapce is doing it everywhere on every platform
- Can't open files without adding its parent directory to the tree view

</details>

**Comment by Cody-Duncan** [comment] 2022-03-31 07:17
Looks like the font rendering is missing anti-aliasing. I ran into a similar rendering issue the windows terminal when the "Text antialiasing" setting was set to "aliased". The `input mono` font has thicker lines, which lessens the effect of aliasing since there isn't as many thin, sharp lines.

I'd re-title this one as "Text Rendering lacks Anti-Aliasing".
I can confirm that happens on windows too.

**Comment by bugadani** [comment] 2022-03-31 09:12
There are  at least two problems at work here:
 - text is being rendered "between pixels"
 - font-kit only loads the extra-thin weight for some reason

**Comment by Twometer** [comment] 2022-04-12 18:57
This not only happens on HiDPI screens, at least on Windows. I have a "regular" screen and text looks like this:
![image](https://user-images.githubusercontent.com/26793103/163033703-b0a1da9f-c3ac-4fd5-a847-fc0c0749b7e0.png)
Exact same Font in VS Code:
![image](https://user-images.githubusercontent.com/26793103/163033788-71f1ab1a-67c0-4212-ab3a-c507883ae12f.png)

**Comment by LoganDark** [comment] 2022-04-12 20:36
> This not only happens on HiDPI screens, at least on Windows. I have a "regular" screen and text looks like this: ![image](https://user-images.githubusercontent.com/26793103/163033703-b0a1da9f-c3ac-4fd5-a847-fc0c0749b7e0.png) Exact same Font in VS Code: ![image](https://user-images.githubusercontent.com/26793103/163033788-71f1ab1a-67c0-4212-ab3a-c507883ae12f.png)

Interesting. There's a lack of color fringing / ClearText, but there's also some weird antialiasing issues despite that.

**Comment by dzhou121** [comment] 2022-05-15 10:47
This should be fixed now by the latest v0.1.0 release.

**Comment by Twometer** [comment] 2022-05-15 13:42
Yes, looks much better now on windows :)

**Comment by bugadani** [comment] 2022-05-15 17:13
Thanks for the feedback. I'm going to close this issue but feel free to reopen if the latest update didn't solve for everybody.

**Closed** 2022-05-15 17:13 UTC
Labels: C-bug, A-ui

**Comment by jtbx** [comment] 2023-01-13 03:21
I still have this issue on version 0.2.5.

**Comment by panekj** [comment] 2023-01-13 08:01
> I still have this issue on version 0.2.5.

Please create new issue.
