### ISSUE TITLE
Not able to open file / folder from command line or finder in MacOS

### ISSUE THREAD

**Issue by Star-Lord-PHB** [lapce/lapce#2313] opened 2023-04-01 01:51 UTC
## Lapce Version

0.2.7

## System information

MacOS Ventura 13.2

## Describe the bug

When trying to open any text file (.md or .c) or folder one of the following methods: 
* right click -> open with -> other -> Lapce
* `open -a /Applications/Lapce.app .` (for folder) OR `open -a /Applications/Lapce.app temp.c` 
Then there will be a window piping up saying that "Lapce cannot open file in the C Source Code format"

## Additional information

![Screenshot 2023-04-01 at 02 49 31](https://user-images.githubusercontent.com/109711159/229260018-340a5f39-ebcb-440a-8c5a-ef4465c0c8a8.png)

![Screenshot 2023-04-01 at 02 50 35](https://user-images.githubusercontent.com/109711159/229260113-4b783b39-6079-4366-82e2-e70fd8f11cd6.png)

**Comment by panekj** [comment] 2023-04-01 06:58
Duplicate of https://github.com/lapce/lapce/issues/1430

**Closed by panekj** 2023-04-01 06:58 UTC
Labels: C-bug
