### ISSUE TITLE
the delete key won't remove text

### ISSUE THREAD

**Issue by SingingBush** [lapce/lapce#170] opened 2022-03-18 18:05 UTC
I highlighted some text with the mouse and pressed delete key but nothing happened. I had to use backspace instead.

**Comment by bugadani** [comment] 2022-03-18 22:57
Possibly a duplicate of #143

Note that by default the `foreward_delete` (sic!, fixed) shortcut was unbound.

**Comment by SingingBush** [comment] 2022-03-21 08:15
I've updated the original #143 issue as it's still a problem. see https://github.com/lapce/lapce/issues/143#issuecomment-1073587076

**Comment by bugadani** [comment] 2022-04-03 09:41
This has been fixed by 08937dbc402d6a795bfcb5ce3e189086784fe086

**Closed by bugadani** 2022-04-03 09:41 UTC
Labels: duplicate, C-feature, A-keymap
