### ISSUE TITLE
Lapce V0.30 error in Artix Linux

### ISSUE THREAD

**Issue by vvvvvx** [lapce/lapce#2757] opened 2023-11-04 06:12 UTC
## Lapce Version
lapce V0.30

## System information
Artix Linux  6.5.7-artix1-1 #1 SMP PREEMPT_DYNAMIC Sun, 15 Oct 2023 22:13:26 +0000 x86_64 GNU/Linux

## Describe the bug
 ERROR lapce_app::keypress: Failed to load from "/home/user/.config/lapce-stable/keymaps.toml": no keymaps
thread 'main' panicked at /build/.cargo/git/checkouts/cosmic-text-fff8c4a78b1e732f/5bfa288/src/buffer_line.rs:192:41:
no default font found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## Additional information
Can't run ,can't see the UI ,can't use.

**Comment by panekj** [comment] 2023-11-04 06:13
Duplicate of https://github.com/lapce/lapce/issues/2748

**Closed by panekj** 2023-11-04 06:13 UTC
Labels: C-bug
