### ISSUE TITLE
plugin menu breaks the program

### ISSUE THREAD

**Issue by icarus-00** [lapce/lapce#2988] opened 2024-02-19 00:24 UTC
## Lapce Version
nightly-5067152

## System information
windows 10

## Describe the bug
the issue can be replicated for me by just scrolling the plugins menu 
basically when you scroll through plugins, you always reach a point where the app just panics.
this basically happens for both portable and installed version and built from source version since v.0.3.1

## Additional information

 ![image](https://github.com/lapce/lapce/assets/147264641/5bfa375b-712a-423a-9b1a-9ec139fbe9a5)

i think the issue can be attributed towards not having a default image for plugins the app is trying to fetch
or maybe the image fetched is of different unsupported format.
a workaround might just to search for specific plugins and avoid scrolling

**Comment by panekj** [comment] 2024-02-19 00:27
Duplicate of https://github.com/lapce/lapce/issues/2988

**Closed by panekj** 2024-02-19 00:27 UTC
Labels: C-bug
