### ISSUE TITLE
Multiple Lapce Windows don't work properly (Windows 10)

### ISSUE THREAD

**Issue by dflock** [lapce/lapce#1085] opened 2022-09-07 21:02 UTC
## Lapce Version

0.2.0

## System information

Windows 10

```
Name                           Value
----                           -----
DisplayVersion                 21H2
ProductName                    Windows 10 Enterprise
CurrentBuildNumber             19044
KeyName                        HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion
Version                        10.0.19044.0
VersionString                  Microsoft Windows NT 10.0.19044.0
```

## Describe the bug

- Open Lapce
- Resize the windows to make sure that it's not full-screen (and to fix #1014)
- Use the command menu to open a new lapce window
- If you now resize the new window smaller, by dragging the edges with the mouse, the original window will sort of... rescale itself to fit into the rectangle of the new windows' size? When it does this, it leaves a white box of it's original size, which it will shrink within. It's not an obvious relationship where resizing one windows rescales the other exactly, but they're definitly connected together in a weird way.
- The new window remains properly scaled and works fine. The original windows is scaled wrongly and doesn't respond correctly to mouse input (presumably you're not clicking where you think) - but keyboard input seems to work - at least pressing Alt+F4 closes it.

### Initial Launch State

![Screenshot 2022-09-07 135532](https://user-images.githubusercontent.com/47756/188977588-7008399d-e6cc-4ccd-964b-73dd30515eb3.jpg)
 (Tiny Resize to fix #1014)
![Screenshot 2022-09-07 135613](https://user-images.githubusercontent.com/47756/188977734-25b82518-4cce-4e79-ac23-73a187113b44.jpg)

### After Creating New Window & Resizing a few times

![Screenshot 2022-09-07 135715](https://user-images.githubusercontent.com/47756/188977769-e2a1da8c-c53f-42fa-9621-bbc1bc7a0196.jpg)

Note the second/new window on top at the right, and the original window underneath, shrunk within it's original extent, which is now filled white.

**Comment by dflock** [comment] 2022-09-12 17:24
I think this probably has the same root cause as #1014, because switching off custom title bars fixes both issues for me.

**Comment by panekj** [comment] 2022-11-08 18:16
This still seems to be a duplicate of #1014

**Closed** 2022-11-08 18:16 UTC
Labels: C-bug, A-ui
