### ISSUE TITLE
Translate the program

### ISSUE THREAD

**Issue by saihaze** [lapce/lapce#2868] opened 2023-12-29 06:50 UTC
## Is your feature request related to a problem? Please describe.

The editor is English only.

## Describe the solution you'd like

Take advantage of `i18n-embed` and `fluent` to translate the program. I can help with Chinese translations.

## Describe alternatives you've considered

`gettext` crates will also do, but I think `fluent` is more advanced.

**Comment by panekj** [comment] 2023-12-29 06:53
Duplicate of https://github.com/lapce/lapce/issues/2236

**Closed by panekj** 2023-12-29 06:53 UTC
Labels: C-feature
