### ISSUE TITLE
add auto save option for files

### ISSUE THREAD

**Issue by dbofmmbt** [lapce/lapce#528] opened 2022-05-20 11:03 UTC
As a user, it would be great to have an option to auto save changed files after some delay when the user stops making changes in the file.

**Comment by ErickHoward** [comment] 2022-05-27 13:36
I would also like this feature because it would allow the rust-analyser information to be updated more easily.

**Comment by moghaazi** [comment] 2022-06-06 21:29
And auto save on Window/Tab changes, as in VS Code.

**Comment by panekj** [comment] 2022-09-13 19:58
Duplicate of #248

**Closed by panekj** 2022-09-13 19:58 UTC
Labels: C-feature
