### ISSUE TITLE
GUI font is a series of rectangular blocks

### ISSUE THREAD

**Issue by GiRiKoTTe** [lapce/lapce#1649] opened 2022-11-05 19:57 UTC
## Lapce Version

v0.2.2

## System information

Windows 10

## Describe the bug
GUI font is rendered as a series of rectangular blocks
![LapceBug](https://user-images.githubusercontent.com/13247441/200138612-0cdc9d5f-ed7c-42fc-951c-c2c73521a7ae.jpg)

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by panekj** [comment] 2022-11-05 19:58
Duplicate of https://github.com/lapce/lapce/issues/940

**Closed by panekj** 2022-11-05 19:58 UTC
Labels: C-bug, duplicate

**Comment by GiRiKoTTe** [comment] 2022-11-05 19:59
Duplicate of https://github.com/lapce/lapce/issues/940
