### ISSUE TITLE
Error in Queue::submit: not enough memory left

### ISSUE THREAD

**Issue by davidak** [lapce/lapce#237] opened 2022-03-23 19:48 UTC
When i open the program, click the blue top-left button and wait, it crashes.

![Screenshot from 2022-03-23 20-38-40](https://user-images.githubusercontent.com/91113/159782356-f9e8ef51-eeb9-4eee-92fb-cab55566fc89.png)

The system has 32 GB RAM and 75% is used. When opening the program, it goes up to 80% before it crashes. The issue is always reproducible in this environment. It also happens when i click the other buttons.

```
[davidak@gaming:~]$ RUST_BACKTRACE=1 lapce
thread 'main' panicked at 'Error in Queue::submit: not enough memory left', /build/lapce-0.0.10-vendor.tar.gz/wgpu/src/backend/direct.rs:214:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: wgpu::backend::direct::Context::handle_error_fatal
   3: wgpu::Queue::submit
   4: <piet_wgpu::context::WgpuRenderContext as piet::render_context::RenderContext>::finish
   5: druid::window::Window<T>::do_paint
   6: druid::win_handler::AppState<T>::paint_winit_window
   7: druid::app::AppLauncher<T>::launch::{{closure}}
   8: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
   9: winit::platform_impl::platform::x11::EventLoop<T>::run
  10: winit::platform_impl::platform::EventLoop<T>::run
  11: winit::event_loop::EventLoop<T>::run
  12: lapce_core::app::lanuch
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
[davidak@gaming:~]$ RUST_BACKTRACE=full lapce
thread 'main' panicked at 'Error in Queue::submit: not enough memory left', /build/lapce-0.0.10-vendor.tar.gz/wgpu/src/backend/direct.rs:214:9
stack backtrace:
   0:     0x55bd3bdabba6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4ceec17bcbdb5c25
   1:     0x55bd3bdc90ec - core::fmt::write::h58e5282d62be0ade
   2:     0x55bd3bd96ce5 - std::io::Write::write_fmt::h66f7942ff99c956d
   3:     0x55bd3bd98590 - std::panicking::default_hook::{{closure}}::hfa0c5e485657cde8
   4:     0x55bd3bd9811d - std::panicking::default_hook::h58da11468c76312b
   5:     0x55bd3bd98bdb - std::panicking::rust_panic_with_hook::h671957801cdd213a
   6:     0x55bd3bdac510 - std::panicking::begin_panic_handler::{{closure}}::h95e203bb3e1d7b92
   7:     0x55bd3bdabcd4 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e335f70cf5032de
   8:     0x55bd3bd98682 - rust_begin_unwind
   9:     0x55bd3a72cfb1 - core::panicking::panic_fmt::hbdb7c8dba8be62e6
  10:     0x55bd3b936553 - wgpu::backend::direct::Context::handle_error_fatal::h4ada4ba6850b91f1
  11:     0x55bd3b936428 - wgpu::Queue::submit::hd9e901d254da9b52
  12:     0x55bd3b9a2d41 - <piet_wgpu::context::WgpuRenderContext as piet::render_context::RenderContext>::finish::h6a4edabbc5cdccb4
  13:     0x55bd3aa6b6f3 - druid::window::Window<T>::do_paint::hd338d1f10391712e
  14:     0x55bd3a96f2fd - druid::win_handler::AppState<T>::paint_winit_window::h7ec60355201e6eba
  15:     0x55bd3a815bd4 - druid::app::AppLauncher<T>::launch::{{closure}}::h0d6896475ddaa6af
  16:     0x55bd3ab89106 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h9c4f5ecb4fb93f20
  17:     0x55bd3ab8a9dd - winit::platform_impl::platform::x11::EventLoop<T>::run::h2d8586e09c7c06ac
  18:     0x55bd3a819514 - winit::platform_impl::platform::EventLoop<T>::run::hbb4ff4f37ef1366c
  19:     0x55bd3a778ebe - winit::event_loop::EventLoop<T>::run::hdc63308a241abd18
  20:     0x55bd3a782d3f - lapce_core::app::lanuch::h579ab5ef7aee6cc7
  21:     0x55bd3a72d1e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdf90fea132dd7eca
  22:     0x55bd3a72d1f9 - std::rt::lang_start::{{closure}}::h9bf041c5425794d4
  23:     0x55bd3bd930c1 - std::rt::lang_start_internal::h275ec2e3ce2206f1
  24:     0x55bd3a72d1d2 - main
  25:     0x7f1145f9e790 - __libc_start_main
  26:     0x55bd3a72d0da - _start
  27:                0x0 - <unknown>
```

---

lapce 0.0.10 from [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=lapce&from=0&size=50&sort=relevance&type=packages&query=Lapce)
NixOS 21.11.336538.64fc73bd74f

**Comment by bugadani** [comment] 2022-04-03 09:09
Hi and thanks for reporting!

Unfortunately, I can't reproduce this on Windows. Can you still crash the latest release version?

**Comment by davidak** [comment] 2022-04-12 17:34
I can still reproduce the same issue.

---

lapce 0.0.12 from [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=lapce&from=0&size=50&sort=relevance&type=packages&query=Lapce)
NixOS 21.11.336824.ccb90fb9e11

**Comment by arjpar** [comment] 2022-04-30 19:46
I can confirm I also have the same issue

lapce 0.0.12
EndeavourOS/Arch Linux

**Comment by panekj** [comment] 2023-12-27 01:49
Should be fixed since almost whole codebase was rewritten

**Closed by panekj** 2023-12-27 01:49 UTC
Labels: C-bug, A-ui, C-perf
