### ISSUE TITLE
Get rid of annoying pop-up on Windows

### ISSUE THREAD

**Issue by oberrich** [lapce/lapce#3220] opened 2024-04-29 17:36 UTC
## Is your feature request related to a problem? Please describe.

When running the app on Windows, you first get a command line pop-up.

## Describe the solution you'd like

Utilize stabilized [RFC-1665: Windows Subsystem](https://rust-lang.github.io/rfcs/1665-windows-subsystem.html) to avoid console allocation for App Window.
I'm not sure how to build this App on Windows otherwise I'd be happy to help to fix this issue, I think first impressions matter.

**Comment by panekj** [comment] 2024-04-29 17:39
Duplicate of https://github.com/lapce/lapce/issues/2813

**Closed by panekj** 2024-04-29 17:39 UTC
Labels: C-feature
