### ISSUE TITLE
FreeBSD: 0.2.1: expected named lifetime parameter

### ISSUE THREAD

**Issue by nunotexbsd** [lapce/lapce#1490] opened 2022-10-12 23:25 UTC
## Lapce Version

0.2.1

## System information

FreeBSD 13.1 amd64, rust 1.63.0

## Describe the bug
Fails to build almost in the end:
```
(...)
error[E0106]: missing lifetime specifier
  --> lapce-data/src/config.rs:38:27
   |
38 |     pub const LAPCE_WARN: &str = "lapce.warn";
   |                           ^ expected named lifetime parameter
   |
help: consider using the `'static` lifetime
   |
38 |     pub const LAPCE_WARN: &'static str = "lapce.warn";
   |                            +++++++
help: consider introducing a named lifetime parameter
   |
37 ~ impl<'a> LapceTheme {
38 ~     pub const LAPCE_WARN: &'a str = "lapce.warn";
   |
(...)
warning: build failed, waiting for other jobs to finish...
*** Error code 101
```
## Additional information

- PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267005
- LOG: https://people.freebsd.org/~eduardo/logs/lapce/lapce-0.2.1/lapce-0.2.1.log

Thanks

**Comment by nunotexbsd** [comment] 2022-10-14 17:31
I can reproduce this problem in https://github.com/lapce/lapce/commit/4a504198166198499a8e122ec16ee68b6e8f6a71 commit

until https://github.com/lapce/lapce/commit/110b65d77bfe26effb545befdd91a9fda478bd7b builds fine.

Any clue?

**Comment by panekj** [comment] 2022-10-14 17:35
Duplicate of https://github.com/lapce/lapce/issues/1405

**Closed by panekj** 2022-10-14 17:35 UTC
Labels: C-bug, duplicate
