### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zhangfq-chemistry** [lapce/lapce#3423] opened 2024-08-10 11:39 UTC
## Lapce Version 
0.4.1

## System information
Ubuntu 22

error[E0658]: use of unstable library feature 'lazy_cell'
 --> /home/zhangfq/.cargo/git/checkouts/floem-69eea0a757d1e3ee/a207ef4/renderer/src/text/layout.rs:1:23
  |
1 | use std::{ops::Range, sync::LazyLock};
  |                       ^^^^^^^^^^^^^^

**Comment by jm-observer** [comment] 2024-08-10 12:35
try this: `cargo run --profile fastdev --bin lapce `

**Comment by panekj** [comment] 2024-08-10 12:37
Duplicate of https://github.com/lapce/floem/issues/543

You need to use Rust 1.80 to compile

**Closed by panekj** 2024-08-10 12:37 UTC
Labels: C-bug
