### ISSUE TITLE
Syntax highlighting not working for me

### ISSUE THREAD

**Issue by gldtn** [lapce/lapce#2747] opened 2023-11-01 23:31 UTC
## Lapce Version

Version 0.3.0

## System information

macOS Sonoma 14.0 Silicone

## Describe the bug
Syntax highlighting is not working  at all for any language.

## Additional information

I have Php Intelephense, HTML LSP, and a couple of themes installed as you can see in the screenshots.

I just tried uninstalling completely all my themes and other plugins, restarted Lapce and no luck.

Restarting the PC didn't help either! I did Upgrade, from previous version, maybe uninstall and install Lapce again?

Screenshots:

![lapce-syntax 2](https://github.com/lapce/lapce/assets/981383/e777319d-d1bd-470e-aa5e-e6bd910cbe16)
![lapce-syntax2](https://github.com/lapce/lapce/assets/981383/7bc9849b-3386-4be4-bad2-08cf086f96b4)

**Comment by laborin** [comment] 2023-11-02 14:57
Syntax highlighting works for me if the file has `.css` or `.js` extension. Any other extension is treated as plain text. Previous version worked great for PHP, JSX, SCSS, etc.

**Comment by pblzd** [comment] 2023-11-03 10:13
I have the same problem with Ruby and the "Ruby (solargraph)" plugin (also on MacOS "Sonoma", v14.1). With v0.2.8 the highlighting worked, with 0.3.0 not anymore.

If I can contribute with more details please let me know.

**Comment by pblzd** [comment] 2023-11-03 11:03
Interestingly syntax highlighting works for JavaScript and CSS files using the "Deno LSP" plugin.

So maybe it's the plugin's fault?

**Comment by starchyunderscore** [comment] 2023-11-06 16:04
Same issue after updating to the latest version, arch linux.

**Comment by nekrondev** [comment] 2023-11-06 17:46
I can also acknowledge the syntax highlight problem on Win10 for PHP files.

**Comment by laborin** [comment] 2023-11-10 21:54
Installed the nightly version and syntax highlighting is working again for PHP files. JSX & SCSS files still looking as plain text. Also noticed that code lens is not working for any file, tried both the key combination and the command palette.

**Comment by ckilb** [comment] 2023-11-14 17:38
I can confirm, syntax highlighting for PHP not working anymore. Mac OS.

**Comment by vimkaf** [comment] 2023-11-30 12:35
Syntax highlighting for PHP is not also working for Windows 11.

**Comment by SamuelPoulin** [comment] 2023-12-01 18:42
Syntax highlighting not working for Ruby on nightly and 0.3.0, but works on 0.2.8. I'm on macos.

**Comment by panekj** [comment] 2023-12-27 05:32
Should be fixed now

**Closed by panekj** 2023-12-27 05:32 UTC
Labels: C-bug, A-syntax

**Comment by laborin** [comment] 2023-12-29 23:47
This is still an issue for JSX files
