### ISSUE TITLE
Window Buttons "Minimize", "Maximize" and Close Button are not Visible on first startup in a small window mode (Windows 10)

### ISSUE THREAD

**Issue by Somsubro-Banerjee** [lapce/lapce#1174] opened 2022-09-12 16:26 UTC
## Lapce Version

0.2.0

## System information

Windows 10

## Describe the bug
When Lapce is started in a small window for the first time it does not show the basic window buttons "Minimize", "Maximize" and "Close", but clicking on the blank space in that region will work and then it goes back to being normal.

Another bug I noticed is while using the "Maximize" button on the application instance on a big window that fits to screen the upper portion of the application where you find the window buttons get cut off in half I am providing the image for your reference below

## Additional information
Start the application in a small window to reproduce this error. Scale the window size to see the icons pop back into the UI
![image](https://user-images.githubusercontent.com/29462545/189701396-e10cfd11-b85f-4f11-a21d-e20b01c7d30e.png)

This Image below describes the second bug I mentioned; see top side of the window
![image](https://user-images.githubusercontent.com/29462545/189705928-543ce56c-9db2-4f10-b548-25aab08458c0.png)

Theory: My theory is that maybe the function that handles window sizing has the problem, I am looking into the code that handles the window sizing. I am fairly new to using Rust but I have developed desktop applications before (using a different framework) ,  if I find anything that might be causing this Issue I will let you guys know.

Peace Out

**Comment by panekj** [comment] 2022-09-12 16:27
duplicate of #1014

**Comment by Somsubro-Banerjee** [comment] 2022-09-12 16:29
@panekj Sorry I couldn't find the exact keyword for this issue before posting

**Closed** 2022-09-12 16:28 UTC
