### ISSUE TITLE
UI scaling through settings

### ISSUE THREAD

**Issue by martinstark** [lapce/lapce#2269] opened 2023-03-21 17:05 UTC
## Is your feature request related to a problem? Please describe.

I have a setup with a 4k monitor where I use individual scaling for each app on my system to make them usable (linux/wayland/xwayland). Lapce is the only app I have installed that doesn't support UI scaling through in-app configuration.

## Describe the solution you'd like

A config in settings to scale the entire UI evenly, by a factor. E.g. `UI Scale: 2.2` for 220% UI scale increase.

## Describe alternatives you've considered

Global monitor scaling is not an option due to scaling issues with xwayland. 

I can increase the font size of the editor and the UI, but this makes the text spill outside of UI elements, and padding does not scale together with the font size. Example of how the UI looks on my system:

![image](https://user-images.githubusercontent.com/901824/226686726-314cfa4b-9739-44fc-b4f4-4de25ea9b20c.png)

Compared to how pretty it looks with proper padding in the sample screenshots on your website:

![image](https://user-images.githubusercontent.com/901824/226686189-6cc21b62-1a5e-42da-b3a2-e0535b2e30d1.png)

**Comment by panekj** [comment] 2023-03-21 20:12
Duplicate of #785

**Closed by panekj** 2023-03-21 20:12 UTC
Labels: C-feature
