### ISSUE TITLE
Future compatibility warning for `winapi 0.2.8`

### ISSUE THREAD

**Issue by bugadani** [lapce/lapce#455] opened 2022-04-25 19:15 UTC
`warning: the following packages contain code that will be rejected by a future version of Rust: winapi v0.2.8` started appearing in rustc 1.62.0 nightly.

**Comment by Diapolo10** [comment] 2022-07-28 07:30
Just wanted to mention that this warning is also appearing on the stable branch, and I'm wondering what part exactly is the cause here.

**Comment by ghishadow** [comment] 2022-07-28 07:51
I think it is most likely due to `mio` https://github.com/lapce/lapce/blob/81c47869bc4a8846ece08ee76cceb6fa3006a80d/lapce-proxy/Cargo.toml#L22 which is using very old winapi v0.2.8 (even latest update of winapi v0.3.9 is 2 years old but used by many important projects) , upstream of `mio` has moved to windows-rs (made by Microsoft), which many rust projects are moving to or already moved (winit recently moved)

**Comment by panekj** [comment] 2023-12-27 02:25
Fixed since we updated alacritty

**Closed by panekj** 2023-12-27 02:25 UTC
Labels: A-dev, Dependency
