### ISSUE TITLE
quote not working with US-intl dead keys layout 

### ISSUE THREAD

**Issue by IlVirtuoso** [lapce/lapce#2409] opened 2023-05-27 19:42 UTC
## Lapce Version
0.2.7
The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

## System information
Ubuntu 23.10
the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04

## Describe the bug

the editor is not writing characters ' or " using the us-intl layout (with dead keys) on ubuntu 23.10

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

**Comment by panekj** [comment] 2023-05-27 19:43
Duplicate of #1094

**Closed by panekj** 2023-05-27 19:43 UTC
Labels: C-bug
