### ISSUE TITLE
LSP crashes due to UNC paths being used on Windows

### ISSUE THREAD

**Issue by thecodrr** [lapce/lapce#1989] opened 2023-01-13 19:01 UTC
## Lapce Version

Nightly (https://github.com/lapce/lapce/commit/e3048264ca8be9f853c14a70ed9c522a109fc831)

## System information

Windows 11

## Describe the bug

For some reason, Lapce is using UNC paths. Opening a terminal inside Lapce starts from:

```
PS Microsoft.PowerShell.Core\FileSystem::\\?\C:\Users\<user>\Sources\Repos\<project>
```

The result is that stuff like `Go to definition` stops working and crashes the LSP:
```
[2023-01-13][23:53:20][lapce_data::proxy][ERROR] lsp server stderr: '\\?\C:\Users\<username>\Sources\Repos\<projectname>'
[2023-01-13][23:53:20][lapce_data::proxy][ERROR] lsp server stderr: CMD.EXE was started with the above path as the current directory.
[2023-01-13][23:53:20][lapce_data::proxy][ERROR] lsp server stderr: UNC paths are not supported.  Defaulting to Windows directory.
```

**Comment by panekj** [comment] 2023-01-13 19:02
duplicate of #1781

**Closed by panekj** 2023-01-13 19:02 UTC
Labels: C-bug

**Comment by panekj** [comment] 2023-01-13 19:06
It's the same issue because we do not handle paths properly in lapce

**Comment by thecodrr** [comment] 2023-01-13 19:08
Ah, I see now. That is why stuff such as `Copy path` start with "\\?\C:\Users\ instead of "C:\Users\"
