### ISSUE TITLE
Add CSS syntax support

### ISSUE THREAD

**Issue by argyleink** [lapce/lapce#313] opened 2022-03-28 04:23 UTC

**Comment by bugadani** [comment] 2022-03-28 06:44
Duplicate of #272

**Comment by Tiggilyboo** [comment] 2022-03-28 11:25
Have added CSS once upstream changes are merged, see https://github.com/lapce/lapce/pull/315
and upstream: https://github.com/tree-sitter/tree-sitter-css/pull/22

**Closed** 2022-03-29 15:53 UTC
