### ISSUE TITLE
GUI bug, icons overlap in 125% scale

### ISSUE THREAD

**Issue by dream7180** [lapce/lapce#2317] opened 2023-04-03 09:24 UTC
GUI icons, e.g. min-restore-close icons, search icon etc, are overlaping, see attched snapshot.
![image](https://user-images.githubusercontent.com/18242221/229468675-815debd1-61d4-4e4d-9918-027830316d11.png)

**Comment by panekj** [comment] 2023-04-03 09:58
duplicate of https://github.com/lapce/lapce/issues/1412

**Closed by panekj** 2023-04-03 09:58 UTC
Labels: C-bug
