### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by PENGUINLIONG** [lapce/lapce#32] opened 2021-12-15 01:01 UTC
On either v0.0.2 release or the latest master (93737031e7ce6dfafefd60df3503c039c2df90eb):
- Cannot drag-n-drop
- Doesn't respond to any of `Ctrl-O`, `Ctrl-N`, `Ctrl-T`
- Window freezes after resize
- The big red close button doesn't close the window
- Terminal doesn't receive `Enter`

Is this project targeting macOS only?

**Comment by seomwan** [comment] 2021-12-19 01:57
On windows 10, with v0.0.4 release:

- [ ] Cannot drag-n-drop - confirmed
- [ ] Doesn't respond to any of `Ctrl-O`, `Ctrl-N`, `Ctrl-T` - yes,
  - but command palette (`Ctrl+P`) works
  - no key bindings  registered in config, don't know how yet
- [x] ~~Window freezes after resize~~ - can't reproduce
- [ ] The big red close button doesn't close the window - confirmed
  - individual files can be closed
  - closing the background terminal works
- [ ] Terminal doesn't receive Enter - confirmed
  - terminal is finicky, the UI sort of shows a new line, but there's no output shown

**Comment by cannero** [comment] 2021-12-22 11:43
On windows 10, with current master [#a61d3b2966f4634ebad6b639692cffd0536d99c0](https://github.com/lapce/lapce/commit/a61d3b2966f4634ebad6b639692cffd0536d99c0)

- [ ] Cannot drag-n-drop - confirmed
- [ ] Doesn't respond to any of Ctrl-O, Ctrl-N, Ctrl-T - yes,
    but command palette (Ctrl+P) works
- [ ] The big red close button doesn't close the window - confirmed
   It looks like this happens also on other platforms https://github.com/lapce/lapce/issues/26
- [ ] Terminal doesn't receive Enter - confirmed
    The problem seems to be the newline character which is sent further to the terminal https://github.com/lapce/lapce/blob/a61d3b2966f4634ebad6b639692cffd0536d99c0/core/src/terminal.rs#L1004
    First I thought the Windows newline `\r\n` must be used, but this shows an additional newline.
    By replacing `\n` with `\r`, the command is evaluated. I haven't found the time to look into this issue more deeply.

**Comment by ghishadow** [comment] 2022-01-03 01:58
> Terminal doesn't receive Enter 

I am currently using Ctrl + m for enter as workaround, also it seems like other [readline](https://www.man7.org/linux/man-pages/man3/readline.3.html) command for movement works.

**Comment by AqilCont** [comment] 2022-01-04 20:35
Is it possible to provide binaries for windows? I don't like installers, and they put stuff in random places and I like to keep stuff portable. Some other issues I encountered:

1. It always opens up on my user dir (`C:\Users\<username>`) even when I invoke it in the command line.
2. There's no way to close the inbuilt terminal, or change it(I haven't looked in settings.toml, but there should still be a way to change it to cmd in the editor itself)
3. You can't use arrow keys on the command overlay. Don't know if this is windows specific, but I only have a windows machine.
4. Typing into the terminal didn't work for me. RIP cargo run :(
3. You can only have one tab open? it only keeps one tab in the main window for some reason.
6. There is a console window that opens up with the app. It's really annoying and clutters my workspace, but it's the only way to close the app?

Sorry, I just put these here since it's an issue related to windows, but I can make separate issues with more screenshots if you want. I just got the editor today and was excited to test it out, but my excitement was beat down pretty quickly :(

**Comment by ghishadow** [comment] 2022-01-05 11:47
Terminal doesn't receive Enter is fixed with 2220062d1f4d816244162faa29fb21a99b40e1bc for me , can you guys/gals test

**Comment by bugadani** [comment] 2022-04-03 07:36
Hi and thank you for reporting these issues!

I'm going to close this to keep the issue list clean.

As far as I can tell, everything should be working except drag-and-drop, which I believe is not properly supported in any other OS either. If any of the issues still stand for you, please feel free to open new issues! However, I would like to ask you to open a separate issue for each problem you have. Thank you!

**Closed by bugadani** 2022-04-03 07:36 UTC
Labels: P-windows
