### ISSUE TITLE
Remote development with containers

### ISSUE THREAD

**Issue by adam-becker** [lapce/lapce#1557] opened 2022-10-19 22:00 UTC
## Is your feature request related to a problem? Please describe.

Something I rely on in VS Code is the ability to use docker containers as a development environment, particularly with `docker-compose` so that I can also get databases and the like.

## Describe the solution you'd like

Given the architecture of lapce, I would think it would be pretty straight forward (albeit deceptively so) to add support for this. The ideal solution would be eventual feature parity with the `Dev Containers` extension in VS Code, though this is fairly "pie in the sky".

## Describe alternatives you've considered

A short-term solution would be to manage the environment outside of lapce, and ensure that the dev container has an SSH server installed. From there, you could connect to it using the existing SSH infrastructure and it _should_ work similarly. A little rough around the edges, but it would suffice as a workaround in the interim.

**Comment by panekj** [comment] 2022-10-19 22:00
duplicate of #1481

**Closed by panekj** 2022-10-19 22:00 UTC
Labels: C-feature

**Comment by adam-becker** [comment] 2022-10-19 22:05
Oops! I had searched before creating and didn't see that one. 😞
