### ISSUE TITLE
Multilingualism

### ISSUE THREAD

**Issue by sharma-shray** [lapce/lapce#3597] opened 2024-11-30 17:08 UTC
Is the app designed for different languages, or is it planned?

with something like https://github.com/longbridgeapp/rust-i18n

**Comment by panekj** [comment] 2024-11-30 17:23
Duplicate of https://github.com/lapce/lapce/issues/2236

> Is the app designed for different language

It currently isn't

**Closed by panekj** 2024-11-30 17:23 UTC
Labels: C-feature
