### ISSUE TITLE
Support for Jupyter

### ISSUE THREAD

**Issue by TigerbyteDev** [lapce/lapce#1160] opened 2022-09-11 20:47 UTC
I want to open my Jupyter Project in Lapce, but it doesn't render properly and is a json-like file. I also can't really run the things in it. I'd love if you could add support for it similiar to Pycharm or VSCode.

**Comment by panekj** [comment] 2022-09-11 20:47
duplicate of https://github.com/lapce/lapce/issues/1037

**Closed** 2022-09-11 20:48 UTC
