### ISSUE TITLE
Unusably large text and context menus, settings categories don't work

### ISSUE THREAD

**Issue by TudbuT** [lapce/lapce#2851] opened 2023-12-13 15:05 UTC
## Lapce Version

nightly-048c510, also present in 0.3.1

## System information

Arch Linux latest

## Describe the bug

Upon starting the editor, the entire UI is too large to do anything. I had to reduce the font size, but in order to go to settings and change the font size in the first place, I had to make the window larger than my screen and move it around awkwardly. After having changed the font size, the UI looked more reasonable at first glance, but the context menus are still about 3x as large as they should be.

Setting the font size also does not always work. I have to type in the new size extremely quickly, or it will go back to the default invisibly. I do not see it go back and future changes get discarded until i scroll down and back up to re-render the field. Now, it is showing the default value and I can change it again with a bit of luck.

Also, when clicking on the settings categories ("UI Settings", "Core settings", etc), I am not always taken to the correct place, no matter the font size. The display of which category you're on has a similar issue. Some sections are skipped or in wrong places. After scrolling to the bottom and back up once, both of this is fixed entirely and persistently until re-opening the settings. 

## Additional information

It seems DPI-awareness is over-compensating heavily. I do have a high-DPI screen, but Lapce seems to think my screen is about the size of a small tablet.

## Screenshots

Large context menu (lapce is full-screen, font size already reduced a bit, but not quite comfortable yet): 
![image](https://github.com/lapce/lapce/assets/48156391/bc3b599b-93d7-489a-b23d-e0f2dc42a97a)

Way too large UI on first open (lapce is windowed, but almost full-screen):
![image](https://github.com/lapce/lapce/assets/48156391/dbd75c60-a304-4f49-823c-ec604277db92)

Category issue
![image](https://github.com/lapce/lapce/assets/48156391/3a90a1cc-0097-4d32-a78e-a760a7abecdb)

**Comment by panekj** [comment] 2023-12-13 15:44
Duplicate of https://github.com/lapce/lapce/issues/2851

**Closed by panekj** 2023-12-13 15:44 UTC
Labels: C-bug

**Comment by TudbuT** [comment] 2023-12-13 19:18
Why are you saying this is a duplicate *of itself*? It quite literally can't be. @panekj

**Comment by panekj** [comment] 2023-12-13 19:19
Wrong link, https://github.com/lapce/lapce/issues/2737

**Comment by TudbuT** [comment] 2023-12-13 19:20
That makes sense. Is the category issue also already reported?

**Comment by panekj** [comment] 2023-12-13 19:20
> That makes sense. Is the category issue also already reported?

https://github.com/lapce/lapce/issues/2759
