### ISSUE TITLE
Allow multiple shortcut combos for same action, and add SHIFT+TAB to outdent default

### ISSUE THREAD

**Issue by ell1e** [lapce/lapce#2699] opened 2023-10-26 01:13 UTC
## Is your feature request related to a problem? Please describe.

The initial problem is I used lapce and it struck me as rather strange and unexpected that `TAB` indents (nice) but `SHIFT+TAB` didn't dedent the selected lines. The reason it threw me off is that lapce is the only code editor I've ever tried where that doesn't fully work. I then found out that `CTRL+[` is also a common shortcut for that, and saw that assigned in the settings, and thought to myself so why don't *both* combinations just do that? I then tried to manually change it to that, and it seems like the settings currently don't allow two separate key combos for the same action, which would also explain why `SHIFT+TAB` doesn't also work by default.

## Describe the solution you'd like

Allow multiple shortcut combos for same action, and then add `SHIFT+TAB` to outdent default in addition to `CTRL+[`.

## Describe alternatives you've considered

I guess you could try to make everyone unlearn `SHIFT+TAB` as an initial expectation, but since it seems to work in the vast majority of other code editors out of the box, that might be a difficult task.

**Comment by panekj** [comment] 2023-10-26 01:19
Duplicate of https://github.com/lapce/lapce/issues/2408

**Closed by panekj** 2023-10-26 01:19 UTC
Labels: C-feature
