### ISSUE TITLE
win10 , 光标错位

### ISSUE THREAD

**Issue by cndeng** [lapce/lapce#1229] opened 2022-09-16 02:54 UTC
## Lapce Version:0.2.0

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

## System information

Windows 10 21H1

## Describe the bug 
鼠标图标跟实际鼠标的坐标点之间差了几十个像素 .

**Comment by bugadani** [comment] 2022-09-16 07:04
Duplicate of #1014

**Closed by bugadani** 2022-09-16 07:04 UTC
