### ISSUE TITLE
In the terminal, text is not selectable and copy-paste isn't working

### ISSUE THREAD

**Issue by liyun-miao** [lapce/lapce#871] opened 2022-07-25 21:20 UTC
In the terminal, I was able to execute commands; however, I wasn't able to select, copy, or paste any content. I would like to be able to select the content in the terminal so that I could copy it to the text editor.
I am using Lapce for Windows (version v0.1.3).

**Comment by BracketMaster** [comment] 2022-08-04 23:53
Same for MacOS.

**Comment by vejnar** [comment] 2022-08-05 22:15
Same for Linux.

**Comment by franklinblanco** [comment] 2022-09-11 22:45
Duplicate of #726

**Comment by panekj** [comment] 2022-09-13 16:21
Implemented in https://github.com/lapce/lapce/pull/1163

**Closed by panekj** 2022-09-13 16:21 UTC
Labels: C-bug, A-terminal

**Comment by Siddhartha351** [comment] 2024-12-06 13:24
cant even change terminal from windows. its completely blank. help
