### ISSUE TITLE
Highlight files/folders with errors

### ISSUE THREAD

**Issue by coffee-is-power** [lapce/lapce#1466] opened 2022-10-09 16:41 UTC
## Is your feature request related to a problem? Please describe.

whenever I change something that a lot of files depend, I have to go the problems tab or open each file to check for errors

## Describe the solution you'd like

The solution to this would be to highlight the files that have errors and/or warnings, and the number of errors and warning next to the name

**Comment by MinusGix** [comment] 2022-10-12 05:02
Duplicate of #532 / #624.

**Closed by MinusGix** 2022-10-12 05:02 UTC
Labels: C-feature
