### ISSUE TITLE
Add support for github co-pilot 

### ISSUE THREAD

**Issue by ethereumdegen** [lapce/lapce#2448] opened 2023-06-11 16:55 UTC
## Is your feature request related to a problem? Please describe.
Feature Request 

## Describe the solution you'd like
I would like github co-pilot to be an extension in Lapce 

## Describe alternatives you've considered
VSCode? :(

**Comment by panekj** [comment] 2023-06-11 17:01
Duplicate of https://github.com/lapce/lapce/issues/1081

**Closed by panekj** 2023-06-11 17:01 UTC
Labels: C-feature
