### ISSUE TITLE
Behaviour with stale socket is confusing

### ISSUE THREAD

**Issue by lnicola** [lapce/lapce#1034] opened 2022-09-04 06:18 UTC
So I saw your release announcement, installed 0.1.3 with the Rust plugin, played with it a little, then upgraded to 0.2. The old plugin was gone, so I reinstalled it. The editor started RA according to the messages below, then got stuck using 100% CPU and crashed after 5-10 seconds:

```
(lapce:1694872): GLib-GIO-CRITICAL **: 09:04:55.046: This application can not open files.
host notificaton experimental/serverStatus not handled
host notificaton experimental/serverStatus not handled
Gdk-Message: 09:06:13.396: Lost connection to Wayland compositor.
```

That's fine, but then it didn't start any more. I had to `strace` it to figure out it was just writing something to `.local/share/lapce-stable/local.sock`.

**Comment by panekj** [comment] 2022-12-22 00:00
Duplicate of #1143

**Closed by panekj** 2022-12-22 00:00 UTC
Labels: C-bug, A-lsp, A-plugins

**Comment by lnicola** [comment] 2022-12-22 19:37
I still think this is a bug. I don't know any other app that behaves like this, and you can't expect users to figure out they have to delete something every time the editor crashes and doesn't start any more.

**Comment by panekj** [comment] 2022-12-22 19:39
> you can't expect users to figure out they have to delete something every time the editor crashes and doesn't start any more.

but it was fixed

**Comment by lnicola** [comment] 2022-12-22 19:53
Okay. Sorry, I missed https://github.com/lapce/lapce/issues/1143#issuecomment-1247188446.
