### ISSUE TITLE
Need an option to disable set_locale_environment.

### ISSUE THREAD

**Issue by danny-su** [lapce/lapce#2024] opened 2023-01-17 05:38 UTC
Need an option to disable set_locale_environment, When I open a new terminal window, I got the following warnings:
![image](https://user-images.githubusercontent.com/12178855/212818528-b5e8a1e3-85ad-408d-93c1-960859b23f06.png)

**Comment by panekj** [comment] 2023-08-13 11:08
Duplicate of #184

**Closed by panekj** 2023-08-13 11:08 UTC
Labels: C-feature, A-terminal
