### ISSUE TITLE
terminal profiles broken again

### ISSUE THREAD

**Issue by maddes8cht** [lapce/lapce#3275] opened 2024-05-19 10:20 UTC
## Lapce Version

nightly -11f36a7

## System information

Windows 10

## Describe the bug
With the current nightly, the formerly closed issue #3244 is back again and worse than before:
- Not only does the before working `settings.toml` i posted in #3244 stop working again (again it always opens powershell)
- in the settings, section terminal, in the `Terminal: default profile` there is only `default`available, the other 
configured terminals have disappeared.
- when i change any settings in the graphical interface, the settings.toml gets shot in the foot (in different ways, see aditional information)

## Additional information

The last item in my list is very inconsistent and not very reproducible, thus i don't have screenshots or .toml file content for this.
I experienced once that the automatically written settings.toml was garbaged in the way that almost all closing bracket like `]` , `}` and even closing `"` had vanished, causing lapce to be stalled when loading. 
I also experienced when changing the `core: Color Theme` setting that i got a `settings.toml`with only the setting for the `core: Color Theme`, all other settings had been deleted. This seems more reproducible.

**Comment by panekj** [comment] 2024-05-26 19:42
Can't reproduce

**Comment by RivenSkaye** [comment] 2024-05-27 13:57
I can reproduce this - on latest stable even. Though slightly different from the original issue because _it's only the first tab_. If I hit the `+` I _do_ get an msys profile terminal.
![image](https://github.com/lapce/lapce/assets/14993038/b721007a-5f05-4e26-8140-b77be671c0f8)
![image](https://github.com/lapce/lapce/assets/14993038/3090ec27-086f-4415-af0b-b21bac45b8d2)
![image](https://github.com/lapce/lapce/assets/14993038/9f6dc650-37ae-424a-bfa3-82efa5ced6b7)

term config:
```toml
[terminal]
font-family = "'Hasklug NF', 'Hasklug Nerd Font'"
font-size   = 14

[terminal.default-profile]
windows = "msys"

[terminal.profiles.msys]
args    = ["--login", "-i"]
command = "C:/msys64/usr/bin/bash.exe"
env     = {MSYSTEM = "MINGW64", CHERE_INVOKING = "1", MSYS2_PATH_TYPE = "inherit", MSYS2_NOSTART = "yes", MSYSCON = "defterm"}
```

@maddes8cht you might wanna test for this as well. Though granted, it kinda sucks to have to open two shells to get the one you want.
You might want to try defterm to ensure it hooks into the calling console host rather than opening its own. nostart shouldn't be needed (it's only relevant when starting through the cmd script AFAICT)

**Comment by panekj** [comment] 2024-05-27 13:58
> I can reproduce this - on latest stable even

An issue that wasn't fixed in stable..

**Comment by RivenSkaye** [comment] 2024-05-27 14:08
I was merely surprised a commit causing an issue in nightly that wasn't noted until a few days before the stable release got through; I figured the time frame would be larger than the few days between this issue and the 0.4.0 release. If I were to be mad about issues in stable, there's be lower hanging fruit.


Small update on the issue at hand: `<msys` makes it open the correct terminal out of view, then clicking the term tab in the bottom panel doesn't cause a powershell session to be started. It does not, unfortunately, bring the terminal into view immediately. So I think something in the terminal tab init is skipping settings. Closing the last terminal and reopening the term tab consistently brings back powershell if that could help for repro

**Comment by panekj** [comment] 2024-05-27 14:09
> term config:
> 
> ```toml
> [terminal]
> font-family = "'Hasklug NF', 'Hasklug Nerd Font'"
> font-size   = 14
> 
> [terminal.default-profile]
> windows = "msys"
> 
> [terminal.profiles.msys]
> args    = ["--login", "-i"]
> command = "C:/msys64/usr/bin/bash.exe"
> env     = {MSYSTEM = "MINGW64", CHERE_INVOKING = "1", MSYS2_PATH_TYPE = "inherit", MSYS2_NOSTART = "yes", MSYSCON = "defterm"}
> ```

this config is invalid btw.
https://docs.lapce.dev/get-started/terminal

**Comment by RivenSkaye** [comment] 2024-05-27 14:15
I can't exactly tell what's invalid about that config tbh; what would be breaking about it?

**Comment by RivenSkaye** [comment] 2024-05-27 14:30
Changing those to match the keys as used in the example does indeed impact the opened env, and removing `CHERE_INVOKING` also makes msys respect the set workdir. But still only on the second and later tabs.

**Comment by panekj** [comment] 2024-05-28 07:37
Fixed via https://github.com/lapce/lapce/commit/af72732768f40995393f60ba7d9ac1353ec26f14

**Closed by panekj** 2024-05-28 07:37 UTC
Labels: C-bug
