### ISSUE TITLE
The application crashes when going to the plugins feature on Windows 10

### ISSUE THREAD

**Issue by fitrarhm** [lapce/lapce#3311] opened 2024-06-08 14:19 UTC
## Lapce Version
0.4.0

## System information
Windows 10

## Describe the bug
The application crashes when going to the plugins feature on Windows 10. To be exact, i'm doing this by click on plugins, scroll down little bit, and the app get crash.

## Additional information

![image](https://github.com/lapce/lapce/assets/63356065/87a341ac-c3e3-4dbb-a209-5ded0a25cabd)

**Comment by panekj** [comment] 2024-06-08 17:21
Duplicate of https://github.com/lapce/lapce/issues/2781

**Closed by panekj** 2024-06-08 17:21 UTC
Labels: C-bug
