### ISSUE TITLE
Please implement spelling checking inside txt and markdown files.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [lapce/lapce#1680] opened 2022-11-10 15:00 UTC
Hello,

Please consider implementing a pluging for spell checking.

For my case it would be nice if it was multi-lingual, in my case English and Portuguese.
I use Hunspell on Linux.

Best regards,
João

**Comment by panekj** [comment] 2022-11-10 15:00
Duplicate of #1595

**Closed by panekj** 2022-11-10 15:00 UTC
Labels: C-feature
