### ISSUE TITLE
Multiple space inserted on window switching

### ISSUE THREAD

**Issue by CreMindES** [lapce/lapce#250] opened 2022-03-24 20:10 UTC
![Peek 2022-03-24 21-08](https://user-images.githubusercontent.com/5306361/160001521-d7751171-b4a5-4c92-aea1-17b9fa620368.gif)

**Comment by MinusGix** [comment] 2022-03-25 00:10
This is currently due to not properly ignoring special keybinds like alt tab (or workspace switching, etc) and so the key still gets sent to the window. Hopefully it will be fixed sometime.

**Comment by dzhou121** [comment] 2022-06-21 10:41
This should be fixed now.

**Comment by hbina** [comment] 2023-01-25 08:42
I cannot reproduce this now. Maybe you can close it @dzhou121 .

**Closed** 2023-01-25 11:27 UTC
Labels: C-bug, A-editor
