### ISSUE TITLE
Click menu: file -> open folder-> Open , it will crash sometimes.

### ISSUE THREAD

**Issue by xuwanjin** [lapce/lapce#2229] opened 2023-03-11 13:39 UTC
## Lapce Version
version: 0.2.6

## System information
MacOS 13.1 (22C65) 16-inch, 2021,Apple M1 Max

## Describe the bug
1. Command + O,  search the lapce, open lapce.
2. click File -> Open Folder, click  open button
3. it will crash. 

## Additional information

- screenshots
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/12403441/224487582-64c325ab-2085-4c2a-89f1-0b1375f4f6bb.png">

- logs
[lapce_crash_log.log](https://github.com/lapce/lapce/files/10948630/lapce_crash_log.log)

- theories about what might be going wrong
- workarounds that you used

**Comment by panekj** [comment] 2023-03-11 13:39
Duplicate of #2200

**Closed by panekj** 2023-03-11 13:39 UTC
Labels: C-bug
