### ISSUE TITLE
Add ability to hide files in the sidebar

### ISSUE THREAD

**Issue by AstroOrbis** [lapce/lapce#2164] opened 2023-02-17 19:44 UTC
Would it be possible to not have specific file/folder names show up in the sidebar?
ex: node_modules, .DS_Store, Cargo.lock, package-lock.json, etc etc etc

**Comment by panekj** [comment] 2023-02-17 19:54
Duplicate of https://github.com/lapce/lapce/issues/811

**Closed by panekj** 2023-02-17 19:54 UTC
Labels: C-feature

**Comment by AstroOrbis** [comment] 2023-02-17 20:00
Thanks - searched "hide" and didn't find anything, guess I didn't look hard enough
