### ISSUE TITLE
I cannot write some Portuguese characters inside Lapce. 

### ISSUE THREAD

**Issue by joaocarvalhoopen** [lapce/lapce#1689] opened 2022-11-11 17:47 UTC
Hello,

in Version 0.2.3 Linux fedora 36

á à ã ẽ é í â ê

simply don't appear.

ç will appear fine.

Thank you,

Best regards,
João

**Comment by sokorototo** [comment] 2022-11-14 11:08
Maybe the fonts aren't installed on your computer? Or the font that you use for lapce does not have the glyphs you need

**Comment by davidrios** [comment] 2022-12-28 20:48
I have the same issue on Debian sid and Sway. From what I can tell the problem is that dead keys don't work.

**Comment by fabiopetrillo** [comment] 2023-02-12 19:03
In fact, it is an issue at the Druid UI toolkit. Lapce inherited this issue.

**Comment by liam-o-marsh** [comment] 2023-03-30 10:14
Is there something else than dead keys at play?
Otherwise, this issue might just be duplicate of https://github.com/lapce/lapce/issues/1094
as for the druid UI toolkit thing… it doesn't help that druid is being discontinued. sounds like a huge pain for lapce.

**Closed** 2023-12-27 03:44 UTC
Labels: C-bug, A-font
