### ISSUE TITLE
MSI installer for Windows is not signed so Windows Defender won't allow it to be run

### ISSUE THREAD

**Issue by monoman** [lapce/lapce#3093] opened 2024-03-22 19:50 UTC
## Lapce Version

Latest installer from site

## System information

Windows 10

## Describe the bug
Windows Defender won't allow to run the installer (also the portable exe is blocked)

**Comment by panekj** [comment] 2024-03-22 22:06
Duplicate of https://github.com/lapce/lapce/issues/1526

**Closed by panekj** 2024-03-22 22:06 UTC
Labels: C-bug
