### ISSUE TITLE
[panic] App doesn't start "no available pixel format"

### ISSUE THREAD

**Issue by merspir** [lapce/lapce#1394] opened 2022-09-29 06:37 UTC
Hello,
I'm using Windows 10 on a VMware Horizon virtual desktop, that I access through VMware Horizon Client.
When I try to execute Lapce 0.2.0 (portable), it throws the following error:

> thread 'main' panicked at 'called Result::unwrap() on an Err value: Other(no available pixel format)'

And mentions druid-shell/src/backend/windows/window.rs:843:26

Screenshot:
![](https://user-images.githubusercontent.com/102377538/192954790-8307a3de-358d-45fe-9f05-161f1cad8610.png)

I opened an issue at Linebender's Druid repo [#2266](https://github.com/linebender/druid/issues/2266) in case that error might happen in other projects that use Druid UI.

**Comment by panekj** [comment] 2022-09-29 06:38
You need an actual GPU in your VM to run Lapce

**Comment by panekj** [comment] 2022-09-29 06:40
Duplicate of #1286

**Closed by panekj** 2022-09-29 06:40 UTC
Labels: C-bug
