### ISSUE TITLE
Web Edition

### ISSUE THREAD

**Issue by Jak2k** [lapce/lapce#2525] opened 2023-07-29 20:07 UTC
## Is your feature request related to a problem? Please describe.

I would like to work at my Android tablet.

## Describe the solution you'd like

A browser version powered by wasm.

## Describe alternatives you've considered

An Android app.

## Additional context

-

**Comment by panekj** [comment] 2023-07-29 20:08
Duplicate of #1642

**Closed by panekj** 2023-07-29 20:08 UTC
Labels: C-feature
