### ISSUE TITLE
Rendering of 'i' in the editor on low DPI monitor

### ISSUE THREAD

**Issue by jrmoulton** [lapce/lapce#2605] opened 2023-09-09 02:48 UTC
## Lapce Version
latest master (this issue has been present for a while)

## System information
macOS

## Describe the bug
Not sure where the issue is but across more than one font rendering of the letter 'i' is off. This only happens when on a lower DPI monitor (not my builtin display). The issue goes away when the font size about doubles. This issue is only on code in the editor an not on other UI elements. 

![Screenshot 2023-09-08 at 8 42 01 PM](https://github.com/lapce/lapce/assets/13090441/a4d9d8a8-5b13-45f7-8ce7-fadd96096119)

**Comment by raspirin** [comment] 2023-11-20 05:12
I come across this issue when I am using my builtin display of macbook pro 2013 with Lapce 0.3.0 and JetBrainsMono. It works fine with other fonts like meslo.

**Comment by panekj** [comment] 2023-12-27 05:05
Duplicate of #2161

**Closed by panekj** 2023-12-27 05:05 UTC
Labels: C-bug
