### ISSUE TITLE
Cannot type in a server name in the Remote SSH text box

### ISSUE THREAD

**Issue by eldar** [lapce/lapce#3260] opened 2024-05-11 17:12 UTC
## Lapce Version

lapce-0.4.0+0ddc216

## System information

Fedora 40 KDE Plasma Desktop

## Describe the bug
I am trying to connect to a remote Linux server by clicking on "Connect to SSH host" which opens a text box on top of the editor, however I cannot type any text in the said textbox - it remains empty.

## Additional information

Here is a screenshot demonstrating the issue

![lapce_bug](https://github.com/lapce/lapce/assets/108657/d0c46cb0-8c64-4b94-a031-b0ac6023f00a)

**Comment by dzhou121** [comment] 2024-05-11 20:38
Can you please try to disable "custom titlebar" in settings.

**Comment by eldar** [comment] 2024-05-12 08:11
I disabled custom title bar, restarted Lapce which made the OS title bar to appear, but I still could not type into the remote SSH text box.

**Comment by simoniz0r** [comment] 2024-05-12 23:16
This is the same as #2857.  Certain input boxes do not take focus correctly.  If you click on something like the button to collapse `Open Editors`, you should be able to type in there.  Same sort of thing happens for the commit input box, the command palette, and a few other things.

**Comment by amrit-citrusleaf** [comment] 2024-05-13 12:55
Bump. The same issue is happening on macOS 14.3.1.
Not sure but looks like Lapce is unable to read the ~/.ssh/config file.

**Comment by panekj** [comment] 2024-05-13 12:56
> Bump. The same issue is happening on macOS 14.3.1.
> Not sure but looks like Lapce is unable to read the ~/.ssh/config file.

Lapce does not read `~/.ssh/config` at all, also please don't post comments like that since they ping people unnecessarily

**Comment by amrit-citrusleaf** [comment] 2024-05-13 12:59
@panekj - I tried contributing with the little knowledge I had. I really like Lapce and want it to grow. I will refrain myself from using it further and contributing with my "useless comments". :)
Apologies for "unnecessarily pinging people" 🙏🏼

**Comment by eldar** [comment] 2024-05-13 15:20
The documentation https://docs.lapce.dev/get-started/remote-development says that uses `~/.ssh/config`. I managed to get the textbox into focus, but I am confused how to specify credentials for a remote server.

**Comment by amrit-citrusleaf** [comment] 2024-05-13 15:23
> > Bump. The same issue is happening on macOS 14.3.1.
> > Not sure but looks like Lapce is unable to read the ~/.ssh/config file.
> 
> Lapce does not read `~/.ssh/config` at all, also please don't post comments like that since they ping people unnecessarily

@panekj - update the documentation if Lapce does not use ~/.ssh/config file. https://docs.lapce.dev/get-started/remote-development

**Comment by panekj** [comment] 2024-05-13 15:31
> The documentation [docs.lapce.dev/get-started/remote-development](https://docs.lapce.dev/get-started/remote-development) says that Lapce uses `~/.ssh/config`.

The documentation states that you can use hostname you configured in `~/.ssh/config`. Lapce doesn't use that config, it's not going to show you anything from that file. Lapce will "use" the hostname, because it's invoking `ssh` command which reads t that file.

**Comment by amrit-citrusleaf** [comment] 2024-05-13 15:34
> > The documentation [docs.lapce.dev/get-started/remote-development](https://docs.lapce.dev/get-started/remote-development) says that Lapce uses `~/.ssh/config`.
> 
> The documentation states that you can use hostname you configured in `~/.ssh/config`. Lapce doesn't use that config, it's not going to show you anything from that file. Lapce will "use" the hostname, because it's invoking `ssh` command which reads t that file.

Got it. So essentially it still "reads" the config file, but only the host name part.
So the real issue is that the host names are not appearing in the UI.

**Comment by panekj** [comment] 2024-05-13 15:37
> So the real issue is that the host names are not appearing in the UI.

There was never any intention for reading SSH config into Lapce or having it display anything more than recent connections (hosts connected to recently), so it's not an issue.
The real issue is that titlebar steals focus from palette input when clicked on.

**Comment by panekj** [comment] 2024-05-13 15:40
I see that the screenshot in the documentation being right under statement of SSH config, can confuse people as to what exactly is happening and I didn't noticed that mistake, this should be updated shortly.
We also had placeholder value when palette input is empty when using SSH connection, but it got lost in UI refactoring.

**Comment by panekj** [comment] 2024-05-14 21:24
Duplicate of https://github.com/lapce/lapce/issues/2857

**Closed by panekj** 2024-05-14 21:24 UTC
Labels: C-bug

**Comment by nguyenvulong** [comment] 2024-10-16 02:27
> Lapce does not read `~/.ssh/config` at all, also please don't post comments like that since they ping people unnecessarily

from the [Lapce docs](https://docs.lapce.dev/get-started/remote-development)

> It will pop up the input box for you to put in the SSH connection details. You can use <user>@<host> or the Host name (do not confuse with HostName in SSH) you configured in your ~/.ssh/config

As I understand, instead of using `<user>@<host>`, I can use the `Host` in  `~/.ssh/config`. That means Lapce does read the file. No?

**Comment by panekj** [comment] 2024-10-16 09:26
> That means Lapce does read the file. No?

No. Exactly under the quoted text there is a warning box:

> Lapce will use your host OpenSSH installation (`ssh` program) to connect to remote target, it doesn't read that file directly so it will not display any host configuration from that file. Palette input in Lapce will show you only recent SSH connections that you made in Lapce itself.
