### ISSUE TITLE
How can I make extension for lapce 

### ISSUE THREAD

**Issue by theabhayprajapati** [lapce/lapce#1409] opened 2022-09-30 12:35 UTC
## Is your feature request related to a problem? Please describe.
As I am coming from VsCode I was using several extensions for syntax highlighting, and bracket colouring. How can use them or make one and publish it?
## Describe the solution you'd like
Make an extension portal where developers can access the extension.

**Comment by Tiggilyboo** [comment] 2022-10-02 10:08
Not 100% on this, but I've started looking at making a LSP plugin for csharp_ls. If you are looking to create a LSP plugin, there is a template here: https://github.com/lapce-community/lapce-volt-template
If you want to install the plugin, you can compile the wasm and dump it in the lapce plugin directory which should get picked up on start.

Otherwise lapce uses tree-sitter parsers for most languages, you can see the support list here: https://github.com/lapce/lapce/issues/272

The whole theming thing is a little over my knowledge. Hope this helps, cheers

**Comment by panekj** [comment] 2023-12-27 02:46
Duplicate of https://github.com/lapce/lapce/issues/123

**Closed by panekj** 2023-12-27 02:46 UTC
Labels: C-feature, A-documentation, A-plugins
