### ISSUE TITLE
Hard Tabs option in the settings

### ISSUE THREAD

**Issue by tulpenkiste** [lapce/lapce#2372] opened 2023-05-13 22:23 UTC
## Is your feature request related to a problem? Please describe.
Whenever I make a new file, I prefer to use hard tabs (personal preference). But I find it annoying having to either copy hard tabs from one file to the new file or just add hard tabs myself in another text editor just for lapce to determine the correct indentation.

## Describe the solution you'd like
I would like there to be an indent type option allowing me to use hard tabs for indents rather than soft tabs.

## Describe alternatives you've considered
None.

## Additional context
Using the latest version of lapce available from Arch Linux's `community` repository.

**Comment by panekj** [comment] 2023-12-27 03:47
Duplicate of https://github.com/lapce/lapce/issues/260

**Closed by panekj** 2023-12-27 03:47 UTC
Labels: C-feature, A-editor

**Comment by boozook** [comment] 2024-01-01 14:17
I suppose this is not a duplicate. Hard tabs is not about replacing tabs with whatever. Hard tabs is about using tabs symbols and possibility to configure visual tab symbol length in pixels or spaces.

**Comment by panekj** [comment] 2024-01-01 14:19
That's what hard tabs are though. Hard tabs = `\t` (tab), soft tabs = ` ` (space)
