### ISSUE TITLE
Terminal does not allow to select text

### ISSUE THREAD

**Issue by FlixCoder** [lapce/lapce#2627] opened 2023-09-20 20:37 UTC
## Lapce Version

Nightly `c539f7a205ec056b6bceed963b61165e9f430353`

## System information

Fedora 38, Wayland

## Describe the bug

Whatever I do, when I click and drag in the terminal, nothing happens. I would expect text to be selected and highlighted up for copying.

## Additional information

None

**Comment by panekj** [comment] 2023-09-20 20:40
This is a regression due to https://github.com/lapce/lapce/issues/2417

**Comment by panekj** [comment] 2024-05-05 15:54
Fixed via https://github.com/lapce/lapce/pull/3106

**Closed by panekj** 2024-05-05 15:54 UTC
Labels: C-bug
