### ISSUE TITLE
Allow mouse buttons for key bindings 

### ISSUE THREAD

**Issue by Tatskaari** [lapce/lapce#910] opened 2022-07-31 15:40 UTC
Related to #559 #604

I'd like to set the following key bindings:

`Ctr-M1` -> jump to definition
`M4` -> jump location backwards
`M5` -> jump location forwards  

Not being able to navigate the codebase properly is a huge productivity loss compared to vs-code and intellij.

**Comment by panekj** [comment] 2022-09-22 07:46
Duplicate of https://github.com/lapce/lapce/issues/446

**Closed by panekj** 2022-09-22 07:46 UTC
Labels: C-feature, A-keymap
