### ISSUE TITLE
Panic when performing go-to definition

### ISSUE THREAD

**Issue by benj-webriq** [lapce/lapce#3216] opened 2024-04-27 14:52 UTC
## Lapce Version

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 
- Version v.0.4.0
## System information

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04
- Windows 11
## Describe the bug
- Lapce proxy panics when trying to "Go to definition" on my react project.
## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used

![image](https://github.com/lapce/lapce/assets/163084454/afa6495a-7bb1-4743-8d6c-228e81b554c0)
![image](https://github.com/lapce/lapce/assets/163084454/f77b9553-7283-4725-8e54-749a3ceff279)

**Comment by panekj** [comment] 2024-05-22 08:59
Duplicate of https://github.com/lapce/lapce/issues/2954

**Closed by panekj** 2024-05-22 08:59 UTC
Labels: C-bug
