### ISSUE TITLE
git ui is not informative enough

### ISSUE THREAD

**Issue by zero-pytagoras** [lapce/lapce#2169] opened 2023-02-19 07:13 UTC
tried to download latest version of lapce: 0.2.5. git shows changes kept in the project but once i commit them, it seems to do nothing. it is not clear whether commit is  saved and there is no indication where i can push to git repo

**Comment by panekj** [comment] 2023-02-19 11:57
Duplicate of https://github.com/lapce/lapce/issues/793

**Closed by panekj** 2023-02-19 11:57 UTC
