### ISSUE TITLE
Typing the ^ character does not work

### ISSUE THREAD

**Issue by hakro** [lapce/lapce#2393] opened 2023-05-21 18:36 UTC
## Lapce Version
0.2.7

## System information
PopOS 22.04

## Describe the bug
Typing the `^` character, in any text field (editor, any search field, or any input), simply does nothing.
It's like the keyboard key that has `^` and `¨` (same key but with Shift), is broken.

I'm on an AZERTY layout, and that key is just to the right of the letter `P`.

Needless to say, that key works everywhere else outside of Lapce.

**Comment by panekj** [comment] 2023-05-21 18:37
What shows up when you try to bind that key?

**Comment by hakro** [comment] 2023-05-21 18:43
Dead 

![2023-05-21_20-43](https://github.com/lapce/lapce/assets/3624853/73fbd9de-9f08-4076-87ed-ed7c53e7efd5)

**Comment by panekj** [comment] 2023-05-21 18:44
That's duplicate of #1094

**Closed** 2023-05-21 18:45 UTC
Labels: C-bug
