### ISSUE TITLE
Why does the ability to redo a change not exist or work?

### ISSUE THREAD

**Issue by Oglo12** [lapce/lapce#1331] opened 2022-09-23 20:40 UTC
## Lapce Version

Lapce: 0.2.0

## System information

Pop!_OS 22.04 LTS (Basically Ubuntu 22.04 LTS)

## Describe the bug
Idk whether this should be filed as a bug or a feature, but it is a big problem that hurts workflow. Where is the ability to redo a change!?

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots
- logs
- theories about what might be going wrong
- workarounds that you used: Cutting the entire code, undoing, and then pasting the code back.

**Comment by Oglo12** [comment] 2022-09-23 20:41
Please fix.

**Comment by panekj** [comment] 2022-09-23 20:41
Duplicate of #1330

**Closed by panekj** 2022-09-23 20:41 UTC
Labels: C-bug
