### ISSUE TITLE
Display errors on old laptop

### ISSUE THREAD

**Issue by maddes8cht** [lapce/lapce#2599] opened 2023-09-07 09:52 UTC
## Lapce Version

Have tried this in about 5 latest releases, partly with portable version, partly with installer.
The screenshot is from version 0.2.8

## System information

Windows 10, with a more than 10 jears old notebook and an intel graphics card.
Processor is: Intel Core i7 2620M, Sandy Bridge
Graphics card is: Intel HD Graphics 3000

## Describe the bug
I have Lapce running successfully on my desktop PC, and I love it.
I have here a very old laptop pc with the above system specifications.
On startup lapce shows up as shown in the screenshot - it is not usable like this.

## Additional information

As you can see the window has a black bar at the top. While the two left buttons, the buttons in the linen area at all, react to mouse clicks, this is not the case with the other control panels at the top edge, also the system buttons for zoom out, zoom in and close do not work. They do work, however, if you click on the area directly above the respective button in the black bar.
To close the program, I have to click above the close button where the close button is usually located in the title bar.
This activates a mousover on the close button visible below, which turns the close field below it red.

- screenshots
![Lapce](https://github.com/lapce/lapce/assets/55592906/a8beab41-2b7d-4d3a-8abd-0671fb8eaf81)

**Comment by MinusGix** [comment] 2023-09-07 10:12
Duplicate of #940

**Closed by MinusGix** 2023-09-07 10:12 UTC
Labels: C-bug
