### ISSUE TITLE
Can't input Chinese in ubuntu 22.04

### ISSUE THREAD

**Issue by fwfsf** [lapce/lapce#877] opened 2022-07-26 12:45 UTC
Now  can display Chinese, but  can't input Chinese in Ubuntu 22.04. The default Chinese input method of Ubuntu 22.04 is from https://github.com/libpinyin/ibus-libpinyin

**Comment by VarLad** [comment] 2022-07-27 22:09
Duplicate of https://github.com/lapce/lapce/issues/319 I guess

**Closed** 2022-09-10 23:22 UTC
Labels: C-bug, A-unicode
