### ISSUE TITLE
Feature request: Provide "User Installer" like VS Code.

### ISSUE THREAD

**Issue by Curious-r** [lapce/lapce#1273] opened 2022-09-19 04:53 UTC
## Is your feature request related to a problem? Please describe.

In current version(0.2.0), the installer on Windows only will intall lapce in system path, however sometime users just want to install lapce for single user.

## Describe the solution you'd like

User Installer can install lapce in `C:\Users\UserName\AppData\Local\Programs\Lapce`

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by panekj** [comment] 2022-09-30 14:23
Duplicate of #498

**Closed by panekj** 2022-09-30 14:23 UTC
Labels: C-feature, P-windows, A-distribution
