### ISSUE TITLE
Command shortcuts are dead on MacOS

### ISSUE THREAD

**Issue by Ducktape10** [lapce/lapce#894] opened 2022-07-28 19:51 UTC
In MacOS some of the key shortcuts/symbolds are not working. For me Commands shortcuts are dead. Only the settings cmd shortcut works.

MacOS Monterey v12.4

Macbook Air 2018

**Comment by MinusGix** [comment] 2022-07-29 21:09
Do you know what key layout you're using? There's some existing bugs for German/Spanish key layouts on MacOS.

**Comment by Ducktape10** [comment] 2022-07-29 21:11
Hungarian layout, but I use karabiner layout changer because of im new macos user. I tried without it but same problem.

**Comment by panekj** [comment] 2023-12-27 02:23
Duplicate of #1094

**Closed by panekj** 2023-12-27 02:23 UTC
Labels: C-bug, P-macos, A-keymap
