### ISSUE TITLE
Broken UI display and no fonts on Windows 11

### ISSUE THREAD

**Issue by toasted226** [lapce/lapce#1318] opened 2022-09-22 16:40 UTC
I am running on Windows 11 version 21H2
The display of the UI elements is inconsistent with where they can be clicked, the window cannot seem to be moved and fonts are missing. Otherwise, the functionality inside of the program is still there e.g. settings menu still works and tooltips are correctly displayed.

![lapce-unusable-windows-11](https://user-images.githubusercontent.com/51060273/191802944-a567d6ca-ca9d-4696-bb6d-f00d3e3141cd.png)

Current hardware information:
CPU Intel Core i7-2640M
RAM 8GB
GPU Intel HD Graphics 3000

**Comment by panekj** [comment] 2022-09-22 17:10
Duplicate of #1083

**Closed by panekj** 2022-09-22 17:10 UTC
