### ISSUE TITLE
Text with more than 3 leading hards tabs is not displayed correctly, but spaces are displayed correctly

### ISSUE THREAD

**Issue by sokorototo** [lapce/lapce#1446] opened 2022-10-05 21:36 UTC
## Lapce Version

Lapce v0.2.0

## System information

Manjaro Linux, kernel version 5.15.

`inxi -F`

![image](https://user-images.githubusercontent.com/53893043/194166452-99b10b0e-8138-4fda-ad4d-b07ef06da73b.png)

## Describe the bug
Any leading hard tabs above 3 are truncated, leading to the code looking all wrong. The screenshots below describe my issue:

How the code should look (in VScode)

![image](https://user-images.githubusercontent.com/53893043/194166722-aef3e7dc-b8e6-4f62-9b08-2450802d9988.png)

How it looks in Lapce:

![image](https://user-images.githubusercontent.com/53893043/194166813-2c2f8a03-b0ce-4dbf-b966-77ea7255eb34.png)

The code in Lapce when using spaces instead of tabs

![image](https://user-images.githubusercontent.com/53893043/194168436-247e513e-58e7-4c61-a41d-08c37ced44e2.png)

## Additional information

- screenshots (see above)
- I am editing this code: https://github.com/sokorototo/vach/blob/main/vach/src/writer/builder/mod.rs#L140
- Something to do with why **all** hard tabs beyond the first three are truncated in this specific scenario?
- workarounds that you used: If I use spaces rather than tabs, the formatting gets fixed. Meaning this behaviour is only native to hard tabs `\t`.

**Comment by hbina** [comment] 2022-10-07 01:55
I can't seem to be able to reproduce this on Windows.

**Comment by panekj** [comment] 2022-10-07 03:57
@sokorototo can you try to reproduce it with latest nightly?

**Comment by sokorototo** [comment] 2022-10-07 12:02
@panekj On the nightly, Lapce does not show this behaviour by default. But, when I tinker around in the font settings, this bug involving tabs comes up. Also, the Rust extension does not trigger IDE features on open Rust projects. When I delete `~/.config/lapce-nightly` the editor settings reset, leading to the issue dissapearing. I am messing around to find what exact setting is causing this

**Comment by Asdow** [comment] 2022-12-04 09:37
I am experiencing this bug on 0.2.4 with Fira Code font

**Comment by sokorototo** [comment] 2022-12-06 08:41
Same here, but with Linux

**Comment by panekj** [comment] 2024-05-06 17:08
This should be fixed now since we rewrote a lot of UI and editor code

**Closed by panekj** 2024-05-06 17:08 UTC
Labels: C-bug, A-font
