### ISSUE TITLE
thread 'main' panicked at 'assertion failed: `(left == right)` (0.0.10)

### ISSUE THREAD

**Issue by eshom** [lapce/lapce#122] opened 2022-03-17 09:34 UTC
OS: Linux.
Compiled from source for opensuse tumbleweed 2022-03-16 snapshot

I tired to change font family. After deleting the current default font name lapce crashed. (Pressed backspace a bunch of times)
Now it doesn't work at all with the following message every time I try to start it:

```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `23`,
 right: `0`', /home/erez/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.10.1/src/loaders/freetype.rs:817:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JackNWhite** [comment] 2022-03-17 13:51
For an immediate fix, you need to open the config (mine is in `~/.config/lapce/settings.toml`) and enter a font name. It doesn't like Terminus, though. :-)

**Comment by eshom** [comment] 2022-03-17 16:50
It did fix the problem for me!
Leaving issue open, because it's easy to reproduce.
Just hold backspace until crash

**Comment by f0x52** [comment] 2022-03-21 23:55
yeah just ran into this as well

**Comment by bugadani** [comment] 2022-04-03 12:26
Thanks for reporting!

I'm not able to reproduce this issue on Windows, could you please confirm if this is still present for you?

**Comment by bugadani** [comment] 2022-04-04 16:56
Thanks for the feedback. I think this might be a platform-specific issue as Windows seems to happily fall back to the "Cascadia Code" included in piet-wgpu.

**Comment by panekj** [comment] 2022-09-30 14:29
This should be fixed already (as we do more font fallbacks)

**Closed by panekj** 2022-09-30 14:29 UTC
Labels: C-bug, P-linux, A-ui
