### ISSUE TITLE
Plugin list not scrollable

### ISSUE THREAD

**Issue by vn971** [lapce/lapce#856] opened 2022-07-23 16:45 UTC
Hi, thanks for developing lapce!
I have an issue. The Plugins panel seems to be non-scrollable for me. I open the panel by clicking the top-left puzzle tile icon, at which point I see some of the plugins such as Rust, C/C++, ... The problem is that I don't see all of them, and I'm not able to scroll this list. Mouse scroll doesn't work (in either direction), arrow buttons and PgUp/PgDn don't work, holding Shift or Ctrl or Alt while attempting to scroll also doesn't work. Effectively I see whatever there is on the screen, but no more.

What could I do to see the rest of the Plugins (and install some potentially)?

Thanks!

**Comment by panekj** [comment] 2022-07-23 16:46
duplicate of #855

**Closed** 2022-07-23 17:56 UTC
