### ISSUE TITLE
Indentation style not configurable

### ISSUE THREAD

**Issue by Timmmm** [lapce/lapce#1415] opened 2022-09-30 17:24 UTC
## Lapce Version

0522da59f24b78a6748364419865f2b65f70deb5

## System information

Windows 10

## Describe the bug

If you create a new document and press tab it will *always* insert 4 spaces, irrespective of the tab width setting. As far as I can tell the code to do this properly mostly exists (`Buffer::indent_style`) but the only way it is set is via auto-detection.

I guess it just needs some configuration options. I think some thought is required because from what I remember tab settings can easily turn out to be a massive mess (they are in VSCode!) because you can be talking about different things:

* Which columns do tab characters align to?
* What is inserted when you press the tab key?

IIRC the VSCode codebase has those concepts separated internally, but actually it's a nightmare to keep track of so in practice they are always the same.

**Comment by panekj** [comment] 2022-09-30 17:28
Duplicate of #782

**Closed by panekj** 2022-09-30 17:28 UTC
Labels: C-bug
