### ISSUE TITLE
Feature request: folding

### ISSUE THREAD

**Issue by Filgas08** [lapce/lapce#2042] opened 2023-01-20 16:33 UTC
I recently started using lapce and the absence of a folding system for loops and functions makes it hard to work on long files.
I think it could be a pretty good feature to be able to fold individual brackets pairs.

**Comment by panekj** [comment] 2023-03-05 22:26
Duplicate of https://github.com/lapce/lapce/issues/749

**Closed by panekj** 2023-03-05 22:26 UTC
Labels: C-feature, A-editor
