### ISSUE TITLE
create file from command line

### ISSUE THREAD

**Issue by hargut** [lapce/lapce#2207] opened 2023-03-03 08:36 UTC
## Is your feature request related to a problem? Please describe.

Starting `lapce` from command line with a file name that does not exist results in a empty `lapce` session.
It is annoying as there are often situations where a new file should be created, using a great editor.

## Describe the solution you'd like

Other editors like `kate` or `vim` open the non-existing file at the location ready for editing & saving.

## Additional context
lapce 0.2.6

https://github.com/lapce/lapce/issues/157
https://github.com/lapce/lapce/issues/752

**Comment by panekj** [comment] 2023-03-03 08:37
Duplicate of https://github.com/lapce/lapce/issues/2109

**Closed by panekj** 2023-03-03 08:37 UTC
Labels: C-feature

**Comment by hargut** [comment] 2023-03-03 08:45
Sorry, I'd overlooked that.
