### ISSUE TITLE
Resize File Explorer and remove Collapse Open Editors

### ISSUE THREAD

**Issue by elibroftw** [lapce/lapce#3177] opened 2024-04-17 21:32 UTC
## Is your feature request related to a problem? Please describe.

Need to be able to collapse open editors and/or resize the ratio between file explorer and the open editor pane

## Describe the solution you'd like

Above

## Describe alternatives you've considered

Using VSCode

## Additional context

![image](https://github.com/lapce/lapce/assets/21298211/b53b3403-d878-40b1-98d1-a12364d0e067)

**Comment by panekj** [comment] 2024-04-17 21:33
Duplicate of https://github.com/lapce/lapce/issues/3063

**Closed by panekj** 2024-04-17 21:33 UTC
Labels: C-feature
