### ISSUE TITLE
Documentation on how to write a plugin

### ISSUE THREAD

**Issue by SOG-web** [lapce/lapce#1892] opened 2023-01-01 09:16 UTC
## Is your feature request related to a problem? Please describe.

Am a flutter dev and I would like to write a plugin for this editor.

## Describe the solution you'd like

I cant find any docs relating to how to write plugin for this editor, A good docs on it will be great.

**Comment by panekj** [comment] 2023-01-01 10:36
duplicate of #123

**Closed by panekj** 2023-01-01 10:36 UTC
Labels: C-feature
