### ISSUE TITLE
File renaming is not handled

### ISSUE THREAD

**Issue by KirillMerz** [lapce/lapce#2002] opened 2023-01-15 14:09 UTC
## Lapce Version
lapce-0.2.5-1

## System information
Manjaro Linux 22.0.0

## Describe the bug
Filename in "Open Editors" and tabs does not changes when file was renamed

## Additional information
![before](https://user-images.githubusercontent.com/62656177/212545415-ee9972af-5d32-49c6-a5a9-779d152f16b4.png)
![after](https://user-images.githubusercontent.com/62656177/212545512-311fcec0-30c3-48ac-9ac4-78d176db78e1.png)

**Comment by panekj** [comment] 2023-01-15 14:10
Duplicate of #1559

**Closed by panekj** 2023-01-15 14:10 UTC
Labels: C-bug
