### ISSUE TITLE
Increase / decrease font size with CMD-+ like VSCode

### ISSUE THREAD

**Issue by erf** [lapce/lapce#1307] opened 2022-09-21 18:34 UTC
## Is your feature request related to a problem? Please describe.

I'd like to increase and decrease font size with `CMD+` and decrease with `CMD-` like VSCode.

**Comment by panekj** [comment] 2022-09-21 18:52
Duplicate of https://github.com/lapce/lapce/issues/785

**Closed by panekj** 2022-09-21 18:52 UTC
Labels: C-feature
