### ISSUE TITLE
Opening a new terminal tab requires tabbing away and back before ready to be used

### ISSUE THREAD

**Issue by kylegoetz** [lapce/lapce#2457] opened 2023-06-14 15:09 UTC
## Lapce Version

0.2.8

## System information

macOS Monterrey

## Describe the bug
If you are in the terminal panel and hit the + to open a second terminal tab, the new tab stays blank until you tab away and back. Then it has the standard terminal text (`Last login`, `username@pwd %` stuff)

**Comment by panekj** [comment] 2023-08-13 11:07
Duplicate of https://github.com/lapce/lapce/issues/2156

**Closed by panekj** 2023-08-13 11:07 UTC
Labels: C-bug, A-terminal
