### ISSUE TITLE
Terminal Settings jumps to wrong place

### ISSUE THREAD

**Issue by RivenSkaye** [lapce/lapce#2808] opened 2023-11-21 14:44 UTC
## Lapce Version
Latest git nightly, freshly built from master (592cbc7b6f672d2ee56447668a25a271d05877bb)

## System information

Windows 10 Pro 22H2 build version 19045.3693

## Describe the bug
When opening the settings menu and clicking the "Terminal Settings" button, the menu is scrolled down to a little over halfway, presenting the bottom of editor settings and the top of UI settings

## Additional information

It seems to scroll _up_ from the UI settings header to the same distance as terminal settings need render space _below_ them. No projects open or anything. Scrolling all the way down and then back up through any other means makes the button work properly. Closing the settings tab subsequently breaks it again.

It highlighting the current scroll position as UI settings is fine, and is due to tracking seeing the overlap area and picking the upper bound; that's normal behavior on a lot of UI toolkits and platforms.

## Other information that can be used to further reproduce or isolate the problem:
![image](https://github.com/lapce/lapce/assets/14993038/b0cff198-4da8-4b7c-ba9b-c9d7f35f23fe)
![image](https://github.com/lapce/lapce/assets/14993038/ee08ca1a-4d71-41b2-b4a9-655a95e71f77)

**Comment by panekj** [comment] 2023-11-21 14:45
Duplicate of https://github.com/lapce/lapce/issues/2759

**Closed by panekj** 2023-11-21 14:45 UTC
Labels: C-bug
