### ISSUE TITLE
Shift-TAB - removing tabs?

### ISSUE THREAD

**Issue by vilords** [lapce/lapce#2311] opened 2023-03-31 15:09 UTC
Went thru the keybindings, but couldn't find an alternative to Shift-TAB.

I love using it, but I don't think it's available in Lapce.

Would be great if you could add this feature.

**Comment by panekj** [comment] 2023-03-31 15:12
Duplicate of https://github.com/lapce/lapce/issues/589

**Closed by panekj** 2023-03-31 15:12 UTC
Labels: C-feature
