### ISSUE TITLE
Ability to click on link in terminal

### ISSUE THREAD

**Issue by rogemus** [lapce/lapce#2845] opened 2023-12-11 10:23 UTC
## Is your feature request related to a problem? Please describe.
Cannot open link in the browser from terminal

## Describe the solution you'd like

I would be great if Lapce have ability to click links in the terminal. Eg. In VS code CMD + press open links in default browsers.

<img width="509" alt="Screenshot 2023-12-11 at 11 19 11" src="https://github.com/lapce/lapce/assets/9271549/80a9feb3-baa2-45dd-bb0c-3f8d415368ba">

**Comment by panekj** [comment] 2023-12-11 10:25
Duplicate of https://github.com/lapce/lapce/issues/1088

**Closed by panekj** 2023-12-11 10:25 UTC
Labels: C-feature
