### ISSUE TITLE
Feature: pass file to lapce / open with lapce

### ISSUE THREAD

**Issue by Lukas1818** [lapce/lapce#623] opened 2022-06-17 13:36 UTC
Sadly executing `lapce some_file.txt` does not open `some_file.txt` in lapce, instead it does only open lapce.

I pretty like the behavior of atom, if I pass a file/foleder.
As example if I call `atom .` atom does fork itself, so I can continue to use the terminal-emulator and open the folder `.`.
It would pretty nice if their will be a similarity behavior for lapce.

**Comment by ghishadow** [comment] 2022-06-17 14:16
Duplicate of https://github.com/lapce/lapce/issues/157

**Closed** 2022-06-18 00:08 UTC
