### ISSUE TITLE
DS Store Issues

### ISSUE THREAD

**Issue by tascord** [lapce/lapce#1674] opened 2022-11-10 01:03 UTC
## Lapce Version
debug (applies to all)

## System information
Windows 11

## Describe the bug
DS Store files are visible, with no way to hide them. They also cause unexpected wrapping issues (assumedly) based off of their encoding type. Presumably, these files, like in vscode and other editors, would be hidden, at least by default, and when opening would not cause such problems.

## Additional information
![image](https://user-images.githubusercontent.com/35181375/200974823-7b82c977-8f6a-4d65-bb08-5978dc4103ed.png)
![image](https://user-images.githubusercontent.com/35181375/200974847-98e02147-5953-407a-91da-8479ec3d7baa.png)

**Comment by panekj** [comment] 2022-11-10 06:17
Duplicate of https://github.com/lapce/lapce/issues/811

**Closed by panekj** 2022-11-10 06:17 UTC
Labels: C-bug
