### ISSUE TITLE
Scrollbar unable to obtain focus in setting window

### ISSUE THREAD

**Issue by moon989** [lapce/lapce#3329] opened 2024-06-13 06:27 UTC
## System information: Win11

Scrollbar unable to obtain focus in setting window. Can not drag 

![image](https://github.com/lapce/lapce/assets/32634377/3ad2cf7c-9866-41a1-8b64-085df5c8a47e)

**Comment by jrmoulton** [comment] 2024-06-13 07:40
https://github.com/lapce/lapce/blob/caab22d09173f286fc36f742259894424fbc735e/lapce-app/src/settings.rs#L1259C5-L1264C7

@dzhou121 removing these lines fixes the issue and the dropdown still works as before. Do they still need to be there?

**Comment by dzhou121** [comment] 2024-06-13 21:43
should be fixed by 28988c8fa2a7e8a0b3e61468038adcbef3b17f24

@jrmoulton The issue is floem https://github.com/lapce/floem/commit/9a9e6c21834ce2f30db2c36d9aadfeb98f899277

**Closed** 2024-06-18 02:11 UTC
Labels: C-bug
