### ISSUE TITLE
Line numbering is not working

### ISSUE THREAD

**Issue by vardhiro** [lapce/lapce#42] opened 2021-12-26 14:28 UTC
It happens so that there are two sections of numbering 

1.  Upto the current line ( where my cursor currently is )
2.  From the next line

**Comment by ghishadow** [comment] 2021-12-26 22:15
any System Info ?

**Comment by bugadani** [comment] 2022-04-03 08:08
Hi and thanks for reporting this issue!

I'm closing this as a duplicate of #35 but I believe the default behavior has also been changed since reporting.

**Closed by bugadani** 2022-04-03 08:08 UTC
Labels: duplicate, A-ui
