### ISSUE TITLE
Edited file notification

### ISSUE THREAD

**Issue by clach04** [lapce/lapce#417] opened 2022-04-12 18:02 UTC
Editing file there is a circle/bullet that appears next to the file name that appears to indicate file modification, issuing an undo (e.g. CTRL-z) to undo all changes and to revert back to the original file does not remove the edited note/mark/circle.

**Comment by clach04** [comment] 2022-04-12 18:03
Link #416

**Comment by bugadani** [comment] 2022-04-12 18:48
Thanks for reporting! This is a duplicate of #245 I believe.

**Closed by bugadani** 2022-04-12 18:48 UTC
Labels: C-bug, duplicate, A-editor
