### ISSUE TITLE
Web IDE

### ISSUE THREAD

**Issue by matifali** [lapce/lapce#1878] opened 2022-12-29 19:19 UTC
A web IDE like vs code server that can be used from the browser.

**Comment by MinusGix** [comment] 2022-12-29 21:53
While this is theoretically possible, it probably won't be happening soon due to the challenges and the amount of other issues to focus on.  
Our fork of druid would have to be modified to render to WebGL. Then there's probably various dependencies which need to be messed with in order to properly compile to webassembly.

**Comment by panekj** [comment] 2023-03-13 02:50
Duplicate of #1642

**Closed by panekj** 2023-03-13 02:50 UTC
Labels: C-feature
