### ISSUE TITLE
can not open file when click  menu "go to definition"  on a function

### ISSUE THREAD

**Issue by moon989** [lapce/lapce#3281] opened 2024-05-22 08:56 UTC
## Lapce Version
nightly-9d016fe

## System information
Windows 11, 

## Describe the bug
can not open file when click method on menu "go to definition" 

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- screenshots

- logs

**Comment by panekj** [comment] 2024-05-22 08:59
Duplicate of https://github.com/lapce/lapce/issues/2954

**Closed by panekj** 2024-05-22 08:59 UTC
Labels: C-bug
