### ISSUE TITLE
Open folder is unresponsive on remote SSH host

### ISSUE THREAD

**Issue by joshreed13** [lapce/lapce#3253] opened 2024-05-09 04:02 UTC
## Lapce Version
v0.4.0

## System information
Windows 11, connecting to Raspberry Pi OS Bookworm

## Describe the bug
Trying Lapce for the first time, very excited to get it to work. When I connect to the remote host with SSH, it connects fine and the terminal is usable. However, when I try "Open Folder", it gives me a prompt that I can type something in, but after hitting enter, it doesn't open the folder. The text that I've entered disappears, but nothing else happens. I've tried all sorts of combinations of relative and absolute paths.

"Open Folder" appears to be working fine for local directories.

## Additional information
I don't see anything relevant in the log file on the local side (is there a log file for the remote side?). I did notice a bunch of spam about `lapce_app::keypress::loader: Keymap ignored`, but that doesn't sound related. I don't know what other diagnostics are available to run, but I'd be happy to gather more info if it would help.

**Comment by panekj** [comment] 2024-05-09 06:05
Duplicate of https://github.com/lapce/lapce/issues/3241

**Closed by panekj** 2024-05-09 06:05 UTC
Labels: C-bug

**Comment by joshreed13** [comment] 2024-05-09 12:31
Thanks for the quick response! For future reference, I was able to use the workaround mentioned in that other ticket, but there's a small catch... you need to run `lapce <path>` in the remote terminal (you're instructing the remote backend to open the folder)
