### ISSUE TITLE
Get rid of annoying flashbang on startup

### ISSUE THREAD

**Issue by oberrich** [lapce/lapce#3221] opened 2024-04-29 17:38 UTC
## Is your feature request related to a problem? Please describe.

When launching the app, you immediately get flash banged by a white window. This not only does attract bugs but also hurts the caffeinated late-night developers.

## Describe the solution you'd like

Cache theme background color, immediately render that color on startup.

**Comment by panekj** [comment] 2024-04-29 17:46
Duplicate of https://github.com/lapce/lapce/issues/2934

**Closed by panekj** 2024-04-29 17:46 UTC
Labels: C-feature
