### ISSUE TITLE
Drag & Drop file to open

### ISSUE THREAD

**Issue by domenicogioia** [lapce/lapce#2619] opened 2023-09-16 18:10 UTC
On MAC when you draf and drop file on the application's icon, the application start and open those file.
This feature is very usefoul on MAC.
Almost any Application support it.

**Comment by panekj** [comment] 2023-09-16 18:11
Duplicate of https://github.com/lapce/lapce/issues/1181

**Closed by panekj** 2023-09-16 18:11 UTC
Labels: C-feature
