### ISSUE TITLE
Win7 support

### ISSUE THREAD

**Issue by lynnux** [lapce/lapce#584] opened 2022-06-07 12:46 UTC
When I run portable version of lapce, get this:
![图片](https://user-images.githubusercontent.com/367894/172381677-7ac23d56-ebf9-465b-95db-ad3b88e368d9.png)
Does lapce plan to support win7?

**Comment by bugadani** [comment] 2022-06-07 19:58
Duplicate of #132

**Closed by bugadani** 2022-06-07 19:58 UTC
Labels: duplicate, P-windows, C-crash 💥
