### ISSUE TITLE
Icon Missing on windows and the msi installer doesnt let user select the install location

### ISSUE THREAD

**Issue by Ulrich-Tonmoy** [lapce/lapce#2981] opened 2024-02-16 11:54 UTC
## Describe the bug
The icon on Portable or the installed version is missing
![Screenshot 2024-02-16 174920](https://github.com/lapce/lapce/assets/65508234/13aca2ca-766d-4f14-9264-76f009078c9c)

And the msi installer doesnt give any option to select custom install location
![Screenshot 2024-02-16 174944](https://github.com/lapce/lapce/assets/65508234/068aa6d4-e1f6-4826-bda3-e390e17a65e7)

**Comment by panekj** [comment] 2024-02-19 00:21
Duplicate of https://github.com/lapce/lapce/issues/1528

**Closed by panekj** 2024-02-19 00:21 UTC
Labels: C-bug
