### ISSUE TITLE
Auto-complete is not working.!

### ISSUE THREAD

**Issue by abdorizak** [lapce/lapce#1132] opened 2022-09-11 06:16 UTC
## Lapce Version
V 0.2.0

The Lapce version you are using, which can be found in "About Lapce" at the top right settings icon. 

## System information
Macbook Air M1

the operating system used, including its version, e.g. Windows 10, Ubuntu 18.04
macOS Monterey

## Describe the bug
it's not making auto complete when i write `console` it's not showing a exactly what i write

<img width="621" alt="Screen Shot 2022-09-11 at 9 09 13 AM" src="https://user-images.githubusercontent.com/59319407/189514985-b623ddf6-e2ef-454d-828b-f20681ad9845.png">

**Comment by ghishadow** [comment] 2022-09-11 06:19
to get autocompletion you need Typescript/Javascript plugin, which is working in progress here https://github.com/panekj/lapce-typescript

**Comment by abdorizak** [comment] 2022-09-11 11:39
> to get autocompletion you need Typescript/Javascript plugin, which is working in progress here https://github.com/panekj/lapce-typescript

ok

**Comment by bugadani** [comment] 2022-09-11 21:29
Closing as a duplicate of #374

**Closed by bugadani** 2022-09-11 21:29 UTC
