### ISSUE TITLE
Allow opening a file to a specific line number.

### ISSUE THREAD

**Issue by mrjbq7** [lapce/lapce#2163] opened 2023-02-17 16:56 UTC
I'm trying to add Lapce support as an editor for the Factor programming language, and we need this feature added for that to work. We know what line number all of our functions are defined at, and we use editors to open those files to the correct line number.

It would be nice to be able to open a single file to a particular line number, some other editors have a convention to specify line number like (e.g., ``lapce file.txt:10``) when opening. Some others use two arguments (e.g., ``lapce file.txt +10``). I don't think there's a universal convention for that.

There was a [reference made to this feature](https://github.com/lapce/lapce/issues/796#issuecomment-1207433939) a few months ago, but it was suggested that it be made as a separate feature request.

**Comment by panekj** [comment] 2023-02-17 16:58
Duplicate of https://github.com/lapce/lapce/issues/1872

**Closed by panekj** 2023-02-17 16:58 UTC
Labels: C-feature
