### ISSUE TITLE
Command Pallet to add Lapce on the terminal in macOS

### ISSUE THREAD

**Issue by shinspiegel** [lapce/lapce#1217] opened 2022-09-15 08:28 UTC
## Is your feature request related to a problem? Please describe.

Like other editors, I would like to start from the command line.
On macOS, VSCode has a special pallet command to add to the terminal.
I could not find an option to add on the command line on the docs. (unless I do it by myself)

## Describe the solution you'd like

We could use a feature similar to VSCode to add the option to start the IDE from the terminal.
That would make it more accessible for people moving from VSCode to Lapce (like myself).

**Comment by panekj** [comment] 2022-09-15 08:39
duplicate of https://github.com/lapce/lapce/issues/1082

**Closed by panekj** 2022-09-15 08:39 UTC
