### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by kojq** [lapce/lapce#2421] opened 2023-06-02 14:44 UTC
Add a feature to drag and drop files into Lapce. That would be useful because it is frustrating to open files from numerous different locations when they're already open in a file manager or the desktop. The feature has already been implemented in several basic text editing applications.

**Comment by panekj** [comment] 2023-06-02 16:35
Duplicate of https://github.com/lapce/lapce/issues/1181

**Closed by panekj** 2023-06-02 16:35 UTC
Labels: C-feature
