### ISSUE TITLE
Crash when sending EOF to terminal pane (version `200acbc`)

### ISSUE THREAD

**Issue by eshom** [lapce/lapce#159] opened 2022-03-18 07:42 UTC
The expected behaviour of sending EOF to terminal is the terminal closing, not the whole program.

To reproduce open terminal inside lapce.
Press CTRL + d

OS: Linux opensuse tumbleweed
tested on lapce commit `200acbc`

Backtrace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lapce-ui/src/status.rs:222:30
stack backtrace:
   0:     0x5598fbd03d4b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b351b19edc68675
   1:     0x5598fbd386ec - core::fmt::write::hda66aa43d7efd443
   2:     0x5598fbcf3952 - std::io::Write::write_fmt::h3aebb987a9dbdcf6
   3:     0x5598fbcfd8b2 - std::panicking::default_hook::{{closure}}::h7e02fcec43867ea3
   4:     0x5598fbcfd4cb - std::panicking::default_hook::h0835f94d5f739358
   5:     0x5598fbcfde12 - std::panicking::rust_panic_with_hook::h88a969557601b593
   6:     0x5598fbd045d2 - std::panicking::begin_panic_handler::{{closure}}::ha092887707fea9e8
   7:     0x5598fbd03e74 - std::sys_common::backtrace::__rust_end_short_backtrace::h79f139e7bde27ff0
   8:     0x5598fbcfd952 - rust_begin_unwind
   9:     0x5598fa6ab511 - core::panicking::panic_fmt::h0b501d90f307324b
  10:     0x5598fa6ab45d - core::panicking::panic::h39d8ed301699854e
  11:     0x5598fa8de067 - <lapce_ui::status::LapceStatusNew as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint::h7dd9c40b6b1fb6c8
  12:     0x5598fa754f68 - druid::core::WidgetPod<T,W>::paint_raw::h6ccdb71c71133a7a
  13:     0x5598fa92ac0b - druid::contexts::PaintCtx::with_save::h4cbabdbe7c0fd019
  14:     0x5598fa760cd5 - druid::core::WidgetPod<T,W>::paint::h2ae885f95549adc8
  15:     0x5598fa718ce5 - <lapce_ui::tab::LapceTabNew as druid::widget::widget::Widget<lapce_data::data::LapceTabData>>::paint::h6e32fbe45465d383
  16:     0x5598fa8b6697 - <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint::he97c3a468a1e4051
  17:     0x5598fa7559c8 - druid::core::WidgetPod<T,W>::paint_raw::h767213c724256d36
  18:     0x5598fa9391ab - druid::contexts::PaintCtx::with_save::he84bf322c0c19b12
  19:     0x5598fa763f48 - druid::core::WidgetPod<T,W>::paint::hf2c096c9327693f8
  20:     0x5598fa869533 - <lapce_ui::window::LapceWindowNew as druid::widget::widget::Widget<lapce_data::data::LapceWindowData>>::paint::hae09f041be76bf3b
  21:     0x5598fa8b5cc7 - <druid::widget::lens_wrap::LensWrap<T,U,L,W> as druid::widget::widget::Widget<T>>::paint::h0f4e1f2c1584e7fb
  22:     0x5598fa75ecc8 - druid::core::WidgetPod<T,W>::paint_raw::hd9a6ea1f9e8b3dc9
  23:     0x5598fa92492b - druid::contexts::PaintCtx::with_child_ctx::hec3964bfd74a2dcf
  24:     0x5598fa6d7170 - tracing::span::Span::in_scope::h4e5e2cca72ebcb5d
  25:     0x5598fa8e97c9 - druid::window::Window<T>::do_paint::h3358957932d44bb8
  26:     0x5598fa86da71 - druid::win_handler::AppState<T>::paint_winit_window::hffe5694514c4b5f0
  27:     0x5598fa6da5cd - druid::app::AppLauncher<T>::launch::{{closure}}::hc9c2f81bce81a548
  28:     0x5598fa6c6551 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::hf629c3e02b8a29b8
  29:     0x5598fa6c6b60 - winit::platform_impl::platform::x11::EventLoop<T>::run::h96bb626df87c1ca0
  30:     0x5598fa6f7ff4 - winit::platform_impl::platform::EventLoop<T>::run::hc201d08f1c06a363
  31:     0x5598fa6d938e - winit::event_loop::EventLoop<T>::run::h464ea3529e5912bf
  32:     0x5598fa6d9bad - druid::app::AppLauncher<T>::launch::ha1a7463585ddee79
  33:     0x5598fa6b4c61 - lapce_ui::app::lanuch::hd3ca664665b3adea
  34:     0x5598fa6abde3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9f28ba5d42953aac
  35:     0x5598fa6abd99 - std::rt::lang_start::{{closure}}::h89a583a208df49f5
  36:     0x5598fbcf0401 - std::rt::lang_start_internal::h0834bb5a35924683
  37:     0x5598fa6abdd2 - main
  38:     0x7f520229a630 - __libc_start_call_main
  39:     0x7f520229a6f0 - __libc_start_main_alias_1
  40:     0x5598fa6abca5 - _start
                               at /home/abuild/rpmbuild/BUILD/glibc-2.35/csu/../sysdeps/x86_64/start.S:115
  41:                0x0 - <unknown>
```

**Comment by bugadani** [comment] 2022-09-20 19:34
Can't reproduce, so I'm closing as fixed. Please reopen if you still experience this issue.

**Closed by bugadani** 2022-09-20 19:34 UTC
Labels: C-bug, A-terminal
