### ISSUE TITLE
Rust File has no syntax highlighting if file not included in the module tree

### ISSUE THREAD

**Issue by jgirardet** [lapce/lapce#1305] opened 2022-09-21 14:52 UTC
## Lapce Version

0.20

## System information

ubuntu 22.04 (popos)

## Describe the bug
Rust File has no syntax highlighting if file not included in the module tree

Just adding for example "mod myfile" in lib.rs will fix it.

I have this problem using trybuild library which runs rust files out of the context of the module tree.

I understand that RA could not be used in this case (saw an issue about it) but I think treesitter could.

Thanks for the enormous work by the way
I

**Comment by panekj** [comment] 2022-09-21 14:53
Duplicate of https://github.com/lapce/lapce/issues/1204

**Closed by panekj** 2022-09-21 14:53 UTC
Labels: C-bug
